### Exploration préparatoire des données ###

In [ ]:
import os
import s3fs
import pandas as pd
import openpyxl

In [ ]:
# Connexion au dépôt de données
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': "https://" + os.environ["AWS_S3_ENDPOINT"]})
# Récupération de la liste des fichiers
fichiers = fs.ls("jacquemmoz")

# Examen des fichiers

## Premier fichier

In [ ]:
# long (42.4s) ==> cellule désactivée
#with fs.open(fichiers[0], mode="rb") as fichier:
#    donnees = pd.read_excel(fichier)

In [ ]:
donnees.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
365252,2025-01-29,800,803,402,NORVILLE ST GER,60115,Imagine R,171
222150,2025-01-20,100,110,275,EUROPE,73617,Amethyste,97
25807,2025-03-18,100,110,362,INVALIDES,71274,NON DEFINI,163
138723,2025-01-14,800,852,938,ST QUENTIN YVE,63812,Forfait Navigo,10828
221544,2025-01-19,800,803,361,INVALIDES,71274,Contrat Solidarité Transport,76
411444,2025-01-10,100,110,555,MONTGALLET,71631,Forfaits courts,189
228180,2025-01-31,100,110,466,LIBERTE,71558,Amethyste,164
276175,2025-03-26,800,803,540,MEUDON VAL FLEU,70412,NON DEFINI,16
221004,2025-01-18,810,801,913,VINCENNES,71651,Autres titres,49
220394,2025-01-18,100,110,696,PTE D.ST-OUEN,72078,Amethyste,305

In [38]:
donnees.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
469371,2025-03-01,800,853,485,LUZARCHES,67177,Forfait Navigo,47
469372,2025-03-01,800,853,536,MERIEL,67065,Amethyste,2
469373,2025-03-01,800,853,536,MERIEL,67065,Imagine R,50
469374,2025-03-01,800,853,568,MONTSOULT,67000,Forfait Navigo,286
469375,2025-03-01,800,853,568,MONTSOULT,67000,Forfaits courts,57

In [39]:
donnees.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
409730,2025-02-02,800,803,639,PETIT VAUX,60985,Forfait Navigo,21
136103,2025-01-04,800,803,832,ST OUEN,72126,Autres titres,3
435954,2025-02-28,100,110,773,SAINT-MARCEL,71092,Imagine R,1536
105801,2025-01-21,100,110,842,SULLY-MORLAND,71201,Imagine R,1838
396296,2025-02-11,100,110,762,ST-DENIS-PTE P,72285,Forfait Navigo,6113
425139,2025-01-08,100,110,318,GARE DU NORD,71410,Imagine R,2572
377231,2025-01-17,800,803,335,GRAVIGNY BAL T12,62667,Autres titres,2
441420,2025-03-14,100,110,492,MAIRIE D.MONT,71785,Contrat Solidarité Transport,3452
149915,2025-02-25,100,110,640,PHIL.AUGUSTE,71751,NON DEFINI,44
335039,2025-03-29,800,804,643,PIERREFITTE STA,72787,Amethyste,88

In [34]:
donnees.dtypes

jour               object
code_stif_trns      int64
code_stif_res      object
code_stif_arret    object
libelle_arret      object
ida                 int64
categorie_titre    object
nb_vald             int64
dtype: object

On voit d'ores et déjà qu'il faudra recoder la colonne 'jour' pour la transformer en type date.
La colonne nb_val est bien un entier.
Les autres colonnes seront utilisables telles quelles : soit on les utilisera comme chaînes de caractères, soit uniquement pour un premier tri des données avant suppression.

## Second fichier

In [43]:
with fs.open(fichiers[1], mode="rb") as fichier:
    donnees = pd.read_excel(fichier)
donnees.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,id_zdc,categorie_titre,nb_vald
0,2025-04-12,100,110,861,TRINITE,71355.0,NON DEFINI,73
1,2025-04-12,100,110,862,TROCADERO,71285.0,Forfaits courts,12487
2,2025-04-12,100,110,862,TROCADERO,71285.0,Imagine R,3092
3,2025-04-12,100,110,864,TUILERIES,71284.0,Amethyste,56
4,2025-04-12,100,110,864,TUILERIES,71284.0,Contrat Solidarité Transport,267

In [44]:
donnees.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,id_zdc,categorie_titre,nb_vald
474201,2025-06-03,800,803,367,ISSY VAL SEI,71016.0,NON DEFINI,67
474202,2025-06-03,800,803,369,IVRY SUR SEINE,424396.0,Forfaits courts,473
474203,2025-06-03,800,803,376,JAVEL,71150.0,Contrat Solidarité Transport,411
474204,2025-06-03,800,803,376,JAVEL,71150.0,Forfaits courts,1147
474205,2025-06-03,800,803,376,JAVEL,71150.0,Imagine R,1172

In [45]:
donnees.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,id_zdc,categorie_titre,nb_vald
465647,2025-06-28,100,110,736,RICHARD LENOIR,73648.0,Forfaits courts,1213
210491,2025-04-05,800,803,590,PORTE MAILLOT,71379.0,Forfaits courts,278
78925,2025-04-23,800,852,858,TRAPPES,63650.0,Autres titres,6
321251,2025-06-08,100,110,144,CHAMPS-ELYSEES,71305.0,Amethyste,144
202743,2025-04-09,800,850,516,MARLES EN BRIE,67604.0,Contrat Solidarité Transport,18
193235,2025-04-02,100,110,892,VICTOR HUGO,71315.0,Forfait Navigo,7174
336879,2025-05-13,100,110,741,ROBESPIERRE,71725.0,Imagine R,1674
223227,2025-05-20,800,804,106,BOUTIGNY,59565.0,Amethyste,3
91332,2025-06-25,800,853,568,MONTSOULT,67000.0,Contrat Solidarité Transport,171
266741,2025-04-07,800,803,793,SERMAISE,59842.0,NON DEFINI,2

In [48]:
donnees.dtypes

jour                object
code_stif_trns       int64
code_stif_res       object
code_stif_arret     object
libelle_arret       object
id_zdc             float64
categorie_titre     object
nb_vald              int64
dtype: object

# Troisième fichier

In [59]:
with fs.open(fichiers[2], mode="rb") as fichier:
    donnees = pd.read_excel(fichier)
donnees.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
0,2025-09-21,810,801,393,71517.0,LA DEFENSE,Forfaits courts,7732
1,2025-09-21,810,801,431,70359.0,LE PARC S.MAUR,NON DEFINI,47
2,2025-09-21,810,801,438,64514.0,LE VESINET-CEN,Autres titres,10
3,2025-09-21,810,801,473,68123.0,LOGNES,Imagine R,521
4,2025-09-21,810,801,473,68123.0,LOGNES,NON DEFINI,28

In [60]:
donnees.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
468221,2025-09-21,800,803,26,60072.0,ARPAJON,Forfait Navigo,314
468222,2025-09-21,800,803,3,69554.0,ABLON,Contrat Solidarité Transport,134
468223,2025-09-21,800,803,31,63134.0,ATHIS MONS,Forfait Navigo,244
468224,2025-09-21,800,803,326,72303.0,GENNEVILLIERS,Forfaits courts,156
468225,2025-09-21,800,803,326,72303.0,GENNEVILLIERS,Imagine R,223

donnees.sample(10)

donnees.dtypes

## Quatrième fichier

In [61]:
with fs.open(fichiers[3], mode="rb") as fichier:
    donnees = pd.read_excel(fichier)
donnees.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
0,2025-10-31,800,803,454,69662,SAULES,Autres titres,1
1,2025-10-31,800,803,454,69662,SAULES,Forfaits courts,188
2,2025-10-31,800,803,788,60987,SAVIGNY SUR ORG,Imagine R,1263
3,2025-10-31,800,803,793,59842,SERMAISE,Amethyste,1
4,2025-10-31,800,803,793,59842,SERMAISE,Forfait Navigo,42

In [62]:
donnees.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
420723,2025-10-09,800,854,527,65827,MAURECOURT,Autres titres,6
7459,2025-12-08,100,110,253,72024,EGLI.DE PANTIN,Contrat Solidarite Transport,1515
30112,2025-11-15,800,854,464,73603,ETANG LA VILLE,Amethyste,5
107672,2025-11-01,810,802,20,69759,ANTONY,Autres titres,12
49218,2025-12-24,810,801,580,70940,NANTERRE-VILLE,Autres titres,26
302254,2025-12-02,100,110,199,71298,CONCORDE,Imagine R,2296
221016,2025-12-24,800,805,967,67625,TOURNAN,NON DEFINI,5
12318,2025-10-08,800,854,92,66741,BONNIERES,Amethyste,7
296689,2025-10-25,800,853,143,65663,CHAMP DE COURSE,Autres titres,10
37739,2025-10-24,800,853,890,67176,VIARMES,Imagine R,76

In [65]:
for fichier in fichiers:
    with fs.open(fichier, mode="rb") as fichier:
        donnees = pd.read_excel(fichier)
donnees.head()

KeyboardInterrupt:

# Concaténation des quatre fichiers en un dataframe Pandas

donnees.tail()

donnees.dtypes