---
title: Exploration préparatoire des données et génération du fichier de données traitées
---

(Les fichiers téléchargés sont stockés ici :
- https://minio.lab.sspcloud.fr/jacquemmoz/partage/validations-reseau-ferre-nombre-validations-par-jour-1er-trimestre.xlsx
- https://minio.lab.sspcloud.fr/jacquemmoz/partage/validations-reseau-ferre-nombre-validations-par-jour-2eme-trimestre.xlsx
- https://minio.lab.sspcloud.fr/jacquemmoz/partage/validations-reseau-ferre-nombre-validations-par-jour-3eme-trimestre.xlsx
- https://minio.lab.sspcloud.fr/jacquemmoz/partage/validations-reseau-ferre-nombre-validations-par-jour-4eme-trimestre.xlsx
)

In [ ]:
%pip install openpyxl
import openpyxl
import pandas as pd
from numpy import datetime64, timedelta64

In [46]:
# Les fichiers partagés sur le service S3 d'Onyxia ont donc une URL de la forme :
fichier = "https://minio.lab.sspcloud.fr/jacquemmoz/partage/validations-reseau-ferre-nombre-validations-par-jour-{}-trimestre.xlsx"

# Examen des fichiers

## Premier fichier

In [47]:
# durée : environ 1 min
donnees1 = pd.read_excel(fichier.format("1er"))

In [48]:
donnees1.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
0,2025-03-07,100,110,487,MADELEINE,71324,Forfaits courts,3387
1,2025-03-07,100,110,49,BARBES-ROCH.,71426,Autres titres,478
2,2025-03-07,100,110,490763,S. GAINSBOURG,490779,Contrat Solidarité Transport,781
3,2025-03-07,100,110,490763,S. GAINSBOURG,490779,Forfait Navigo,2880
4,2025-03-07,100,110,490763,S. GAINSBOURG,490779,Imagine R,1158

In [49]:
donnees1.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
469371,2025-03-01,800,853,485,LUZARCHES,67177,Forfait Navigo,47
469372,2025-03-01,800,853,536,MERIEL,67065,Amethyste,2
469373,2025-03-01,800,853,536,MERIEL,67065,Imagine R,50
469374,2025-03-01,800,853,568,MONTSOULT,67000,Forfait Navigo,286
469375,2025-03-01,800,853,568,MONTSOULT,67000,Forfaits courts,57

In [50]:
donnees1.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
197819,2025-03-06,800,803,474,LONGJUMEAU,62977,Imagine R,76
197930,2025-03-06,800,805,1232,PORTE MAILLOT RER E,71379,Autres titres,91
260563,2025-02-08,800,854,82,BOIS COLOMBES,72179,Contrat Solidarité Transport,503
379239,2025-01-25,100,110,250,EDGAR QUINET,71108,Imagine R,1307
124292,2025-02-12,800,852,906,VILLEPREUX,64145,Forfait Navigo,1520
221764,2025-01-19,800,852,538,MEUDON,70515,Forfaits courts,58
266383,2025-02-12,800,800,1202,EPINAY VIL T11,65227,NON DEFINI,9
392973,2025-02-01,800,804,482,LOUVRES,69300,Forfait Navigo,674
286909,2025-02-20,800,805,446,BOULLEREAUX,73098,NON DEFINI,29
105836,2025-01-21,100,ND,ND,Inconnu,999999,Forfaits courts,3

In [51]:
donnees1.dtypes

jour               object
code_stif_trns      int64
code_stif_res      object
code_stif_arret    object
libelle_arret      object
ida                 int64
categorie_titre    object
nb_vald             int64
dtype: object

> On voit d'ores et déjà qu'il faudra recoder la colonne 'jour' pour la transformer en type date.
La colonne nb_val est bien un entier.
Les autres colonnes seront utilisables telles quelles : soit on les utilisera comme chaînes de caractères, soit uniquement pour un premier tri des données avant suppression.

## Deuxième fichier

In [52]:
donnees2 = pd.read_excel(fichier.format("2eme"))

In [53]:
donnees2.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,id_zdc,categorie_titre,nb_vald
474201,2025-06-03,800,803,367,ISSY VAL SEI,71016.0,NON DEFINI,67
474202,2025-06-03,800,803,369,IVRY SUR SEINE,424396.0,Forfaits courts,473
474203,2025-06-03,800,803,376,JAVEL,71150.0,Contrat Solidarité Transport,411
474204,2025-06-03,800,803,376,JAVEL,71150.0,Forfaits courts,1147
474205,2025-06-03,800,803,376,JAVEL,71150.0,Imagine R,1172

In [54]:
donnees2.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,id_zdc,categorie_titre,nb_vald
183321,2025-05-30,100,110,459,LES GOBELINS,71076.0,Amethyste,296
377669,2025-04-04,800,853,815,ST DENIS,72323.0,Forfait Navigo,15150
341347,2025-04-03,100,110,767,ST-GERM.D.PRES,71216.0,Amethyste,256
192793,2025-04-01,810,802,795,SEVRAN BEAUDOTT,73491.0,Forfaits courts,391
237646,2025-06-20,100,110,808,STALINGRAD,71961.0,NON DEFINI,290
347049,2025-04-18,100,110,741,ROBESPIERRE,71725.0,Amethyste,460
192860,2025-04-02,100,110,16,ANATOLE FRANCE,71519.0,Contrat Solidarité Transport,774
258378,2025-06-05,800,854,86,BOISSY L AILLER,67056.0,Contrat Solidarité Transport,14
380087,2025-04-10,810,801,431,LE PARC S.MAUR,70359.0,Imagine R,1316
388144,2025-04-01,800,804,322,GARGES SARCELLE,65582.0,Contrat Solidarité Transport,7887

In [55]:
donnees2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474206 entries, 0 to 474205
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   jour             474206 non-null  object
 1   code_stif_trns   474206 non-null  int64
 2   code_stif_res    474206 non-null  object
 3   code_stif_arret  474206 non-null  object
 4   libelle_arret    474206 non-null  object
 5   id_zdc           473185 non-null  float64
 6   categorie_titre  474206 non-null  object
 7   nb_vald          474206 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 28.9+ MB

## Troisième fichier

In [56]:
donnees3 = pd.read_excel(fichier.format("3eme"))

In [57]:
donnees3.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
468221,2025-09-21,800,803,26,60072.0,ARPAJON,Forfait Navigo,314
468222,2025-09-21,800,803,3,69554.0,ABLON,Contrat Solidarité Transport,134
468223,2025-09-21,800,803,31,63134.0,ATHIS MONS,Forfait Navigo,244
468224,2025-09-21,800,803,326,72303.0,GENNEVILLIERS,Forfaits courts,156
468225,2025-09-21,800,803,326,72303.0,GENNEVILLIERS,Imagine R,223

In [58]:
donnees3.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
96523,2025-07-11,100,110,352,415852.0,HOTEL DE VILLE,NON DEFINI,531
284818,2025-07-04,800,803,3,69554.0,ABLON,Forfaits courts,192
100125,2025-07-16,800,805,965,462934.0,OZOIR LA FERRIE,Autres titres,12
154561,2025-09-14,800,851,922,61630.0,VULAINES SUR SE,Imagine R,22
401357,2025-09-30,100,110,171,461505.0,CHATILLON-MON.,NON DEFINI,124
223053,2025-08-16,100,110,736,73648.0,RICHARD LENOIR,NON DEFINI,38
452316,2025-09-01,100,110,10,71030.0,ALESIA,Amethyste,297
221962,2025-08-02,810,802,287,70133.0,FONTENAY-AUX-R,Imagine R,397
94832,2025-07-27,800,800,48090,73731.0,Saint-Cyr T13,Forfait Navigo,58
189324,2025-07-20,100,110,696,72078.0,PTE D.ST-OUEN,Amethyste,270

In [59]:
donnees3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468226 entries, 0 to 468225
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   jour             468226 non-null  object
 1   code_stif_trns   468226 non-null  int64
 2   code_stif_res    468226 non-null  object
 3   code_stif_arret  468226 non-null  object
 4   id_zdc           467625 non-null  float64
 5   libelle_arret    468226 non-null  object
 6   categorie_titre  468226 non-null  object
 7   nb_vald          468226 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 28.6+ MB

## Quatrième fichier

In [60]:
donnees4 = pd.read_excel(fichier.format("4eme"))

In [61]:
donnees4.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
331089,2025-12-23,800,854,96,64301,BOUGIVAL,Imagine R,95
450394,2025-10-30,810,801,913,71651,VINCENNES,Forfait Navigo,18084
335007,2025-12-30,100,110,573,73653,MOUTON-DUVERN.,Imagine R,477
167934,2025-11-23,800,854,1209,486999,TRAITE DE ROME T12,Forfait Navigo,25
12651,2025-10-09,100,110,220,71834,COURONNES,Amethyste,567
111430,2025-10-21,810,802,20,69759,ANTONY,NON DEFINI,161
235192,2025-12-18,100,110,180,73622,CHEMIN-VERT,Forfaits courts,1010
234862,2025-12-16,800,854,448,65985,CLAIRIERES,Imagine R,114
428650,2025-11-22,100,110,759,73690,SAINT-AUGUSTIN,Autres titres,49
270456,2025-11-09,100,110,269,71485,ESPLANADE DEF.,Contrat Solidarite Transport,431

In [62]:
donnees4.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
480640,2025-10-04,800,852,797,463754,SEVRES RG,Forfait Navigo,657
480641,2025-10-04,800,852,813,73731,ST CYR,Contrat Solidarite Transport,217
480642,2025-10-04,800,852,938,63812,ST QUENTIN YVE,Amethyste,131
480643,2025-10-04,800,852,938,63812,ST QUENTIN YVE,Imagine R,1660
480644,2025-10-04,800,852,846,64194,TACOIGNIERES,Amethyste,1

In [63]:
donnees4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480645 entries, 0 to 480644
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   jour             480645 non-null  object
 1   code_stif_trns   480645 non-null  int64
 2   code_stif_res    480645 non-null  object
 3   code_stif_arret  480645 non-null  object
 4   id_zdc           480645 non-null  int64
 5   libelle_arret    480645 non-null  object
 6   categorie_titre  480645 non-null  object
 7   nb_vald          480645 non-null  int64
dtypes: int64(3), object(5)
memory usage: 29.3+ MB

# Concaténation des quatre fichiers en un dataframe Pandas - étude de ce dataframe

On utilise les dataframes issus de l'examen des fichiers dans la partie précédente. C'est pour cela qu'on n'a pas recours à une boucle `for`.

In [64]:
df = pd.concat((donnees1, donnees2, donnees3, donnees4))
# vérification de la longueur du dataframe concaténé
len(df) == len(donnees1) + len(donnees2) + len(donnees3) + len(donnees4)

True

In [65]:
df.sample(15)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald,id_zdc
255271,2025-01-23,100,110,780,ST-SEBASTIEN.F,71777.0,Amethyste,96,NaN
282319,2025-06-30,800,804,333,GOUSSAINVILLE,NaN,NON DEFINI,75,66535.0
394193,2025-09-23,100,110,729,REPUBLIQUE,NaN,Forfaits courts,7637,71311.0
354082,2025-07-22,800,804,556,MONTGERON,NaN,Forfait Navigo,2722,63072.0
205591,2025-04-27,810,801,129,CERGY PREFECTUR,NaN,Imagine R,1624,66696.0
406568,2025-12-12,800,850,267,ESBLY,NaN,Amethyste,9,68653.0
265005,2025-05-08,800,850,570,MORTCERF,NaN,Forfaits courts,1,67805.0
356815,2025-07-13,100,110,703,PORTE D'ITALIE,NaN,NON DEFINI,90,70596.0
66284,2025-02-02,100,110,773,SAINT-MARCEL,71092.0,Contrat Solidarité Transport,175,NaN
191377,2025-04-21,800,853,675,PONTOISE,NaN,Autres titres,6,66816.0
237947,2025-02-27,800,854,211,CORMEILLES,65399.0,Imagine R,852,NaN
457809,2025-09-14,800,854,883,VERNOUILLET,NaN,Amethyste,19,65691.0
468652,2025-06-25,800,804,482,LOUVRES,NaN,Forfaits courts,266,69300.0
186972,2025-03-21,100,110,199,CONCORDE,71298.0,Amethyste,145,NaN
381307,2025-07-23,100,110,490763,S. GAINSBOURG,NaN,Forfaits courts,570,490779.0

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1892453 entries, 0 to 480644
Data columns (total 9 columns):
 #   Column           Dtype
---  ------           -----
 0   jour             object
 1   code_stif_trns   int64
 2   code_stif_res    object
 3   code_stif_arret  object
 4   libelle_arret    object
 5   ida              float64
 6   categorie_titre  object
 7   nb_vald          int64
 8   id_zdc           float64
dtypes: float64(2), int64(2), object(5)
memory usage: 144.4+ MB

Dans le jeu de données, on ne conservera pas les champs `code_stif_arret`, `ida`, et `id_zdc`.
On filtrera les données intéressantes sur les champs `code_stif_trns` et `code_stif_res`.
On va prendre chaque colonne qu'on conservera ou sur laquelle on filtrera, la mettre en forme et le cas échéant vérifier sa conformité.

## Colonne `jour`
On convertit cette colonne en type `date`, puis on vérifie que chaque jour de l'année 2025 est bien présent (comparaison au set `annee`de l'ensemble des jours de 2025).

In [67]:
df["jour"] = pd.to_datetime(df["jour"])
annee = {datetime64("2025-01-01") + timedelta64(i) for i in range(365)}
print(set(df["jour"]) == annee)  # pd.unique(df["jour"]) peut calculer plus vite
# ou annee.difference(set(df["jour"]))

True

## Colone `code_stif_trns`

Il s'agit du code du transporteur. Seule la RATP, code 100 nous intéresse.

In [68]:
pd.unique(df["code_stif_trns"])

array([100, 760, 762, 800, 810, 761, 764])

In [69]:
df = df[df["code_stif_trns"] == 100]

## Colonne `code_stif_res`

Il s'agit du code du réseau. Seul le code 110, correspondant au métro, nous intéresse.

In [70]:
pd.unique(df["code_stif_res"])

array(['110', 'ND'], dtype=object)

On doit éliminer les données du réseau 'ND'. Cependant on regarde avant la proportion de `nb_vald` (la variable quantitative que l'on va étudier) que cela représente.

In [71]:
df[df["code_stif_res"] == "ND"]["nb_vald"].sum() / df["nb_vald"].sum()

np.float64(0.000417352438591083)

Ce nombre est négligeable.

In [72]:
df = df[df["code_stif_res"] == "110"]

## Colonne `libelle_arret`

In [73]:
sorted(pd.unique(df["libelle_arret"]))

['ABBESSES',
 'AIME CESAIRE',
 'ALESIA',
 'ALEXANDR.DUMAS',
 'ALFORT-ECOLE V',
 'ALMA-MARCEAU',
 'ANATOLE FRANCE',
 'ANTONY',
 'ANVERS',
 'ARGENTINE',
 'ARTS.METIERS',
 'ASSEMBLEE NAT.',
 'AUBERV.4 CHEM.',
 'AV.EMILE ZOLA',
 'AVRON',
 'BALARD',
 'BARBARA',
 'BARBES-ROCH.',
 'BASTILLE',
 'BEL AIR',
 'BELLEVILLE',
 'BERAULT',
 'BERCY',
 'BIBLIOTHEQUE',
 'BILLANCOURT',
 'BIR-HAKEIM',
 'BLANCHE',
 'BOB.P.PICASSO',
 'BOB.R.QUENEAU',
 'BOISSIERE',
 'BOLIVAR',
 'BONNE NOUVELLE',
 'BOTZARIS',
 'BOUCICAUT',
 'BOULETS-MONTR.',
 'BOULOGNE-J.J.',
 'BOULOGNE-ST.CL',
 'BOURSE',
 'BREGUET-SABIN',
 'BROCHANT',
 'BUTTES-CHAUM.',
 'BUZENVAL',
 'CADET',
 'CAMBRONNE',
 'CAMPO-FORMIO',
 'CARD.LEMOINE',
 'CARREF.PLEYEL',
 'CENSIER DAUB.',
 'CH.D.G.ETOILE',
 'CH.D.VINCENNES',
 'CHAMPS-ELYSEES',
 'CHARDON-LAGACH',
 'CHARENTON-ECO.',
 'CHARL.MICHELS',
 'CHARONNE',
 "CHATEAU D'EAU",
 'CHATEAU ROUGE',
 'CHATEAU-LANDON',
 'CHATELET',
 'CHATILLON-MON.',
 "CHAUSS.D'ANTIN",
 'CHEMIN-VERT',
 'CHEVALERET',
 'CHEVILLY-LARUE',
 'CITE',
 'CLICHY ST-OUEN',
 'COLONEL FABIEN',
 'COMMERCE',
 'CONCORDE',
 'CONVENTION',
 'CORENT.CARIOU',
 'CORENT.CELTON',
 'CORVISART',
 'COT. BEAUCLAIR',
 'COUR ST-EMILI.',
 'COURCELLES',
 'COURONNES',
 'CRETEIL-ECHAT',
 'CRETEIL-P. LAC',
 'CRETEIL-PREF.',
 'CRETEIL-UNIV.',
 'CRIMEE',
 'CRX.DE CHAVAUX',
 'DANUBE',
 'DAUMESNIL',
 'DENFERT-ROCH.',
 'DUGOMMIER',
 'DUPLEIX',
 'DUROC',
 'EC.MILITAIRE',
 'EDGAR QUINET',
 "EGLI.D'AUTEUIL",
 'EGLI.DE PANTIN',
 'ESPLANADE DEF.',
 'ETIENNE MARCEL',
 'EUROPE',
 'EXELMANS',
 'F.D.ROOSEVELT',
 'FAIDHERBE-CHA.',
 'FALGUIERE',
 'FELIX FAURE',
 'FILLES DU CALV',
 "FORT D'AUBERV.",
 'FR. POPULAIRE',
 'FUNICULAIRE',
 'GABRIEL PERI',
 'GAITE',
 'GALLIENI',
 'GAMBETTA',
 "GARE D'AUSTER.",
 "GARE DE L'EST",
 'GARE DE LYON',
 'GARE DU NORD',
 'GARIBALDI',
 'GDS BOULEVARDS',
 'GEORGE V',
 'GLACIERE',
 'GONCOURT',
 'GUY MOQUET',
 'HAVR.CAUMARTIN',
 'HOCHE',
 'HOP. BICETRE',
 'HOTEL DE VILLE',
 'IENA',
 'INVALIDES',
 'J.BONSERGENT',
 'JASMIN',
 'JAURES',
 'JAVEL',
 'JOURDAIN',
 'JULES JOFFRIN',
 'JUSSIEU',
 'KLEBER',
 'KREML.BICETRE',
 "L'HAY-LES-ROSE",
 'LA CHAPELLE',
 'LA COURNEUVE',
 'LA DEFENSE',
 'LA DHUYS',
 'LA FOURCHE',
 'LA MOTTE-PICQ.',
 'LA MUETTE',
 'LAMARCK-CAUL.',
 'LATOUR-MAUB.',
 'LAUMIERE',
 'LE PELETIER',
 'LEDRU-ROLLIN',
 'LES AGNETTES',
 'LES COURTILLES',
 'LES GOBELINS',
 'LES HALLES',
 'LES SABLONS',
 'LIBERTE',
 'LIEGE',
 'LOUIS BLANC',
 'LOUISE MICHEL',
 'LOURMEL',
 'LOUVRE',
 'LUCIE AUBRAC',
 'M. MONTROUGE',
 'M.ANGE-AUTEUIL',
 'M.ANGE-MOLITOR',
 'MABILLON',
 'MADELEINE',
 'MAIRIE CLICHY',
 "MAIRIE D'AUBERVILLIERS",
 "MAIRIE D'ISSY",
 "MAIRIE D'IVRY",
 'MAIRIE D.LILAS',
 'MAIRIE D.MONT',
 'MAIRIE ST-OUEN',
 'MAIS.ALF-JUIL.',
 'MAIS.ALF-STADE',
 'MAISON BLANCHE',
 'MALAK-P.VANVES',
 'MALAK.ET.DOLET',
 'MALESHERBES',
 'MARAICHERS',
 'MARCADET-POIS.',
 'MARCEL SEMBAT',
 'MARX DORMOY',
 'MAUBERT-MUTUA.',
 'MENILMONTANT',
 'MICHEL BIZOT',
 'MIRABEAU',
 'MIROMESNIL',
 'MONCEAU',
 'MONTGALLET',
 'MONTPARNASSE',
 'MONTREUIL HOP.',
 'MOUTON-DUVERN.',
 'N.D.DE-LORETTE',
 'N.D.DES-CHAMPS',
 'NATION',
 'NATIONALE',
 'OBERKAMPF',
 'ODEON',
 'OLYMPIADES',
 'OPERA',
 'OURCQ',
 'PALAIS-ROYAL',
 'PARMENTIER',
 'PASSY',
 'PASTEUR',
 'PELLEPORT',
 'PERE-LACHAISE',
 'PEREIRE',
 'PERNETY',
 'PHIL.AUGUSTE',
 'PICPUS',
 'PIERRE CURIE',
 'PIGALLE',
 'PLACE CLICHY',
 "PLACE D'ITALIE",
 'PLACE D. FETES',
 'PLACE MONGE',
 'PLAISANCE',
 'POISSONNIERE',
 'PONT CARDINET',
 'PONT D.NEUILLY',
 'PONT DE SEVRES',
 'PONT LEVALLOIS',
 'PONT MARIE',
 'PONT-NEUF',
 "PORTE D'ITALIE",
 "PORTE D'IVRY",
 'PORTE D.CLIGN.',
 'PORTE D.LILAS',
 'PORTE D.VANVES',
 'PORTE D.VERS.',
 'PORTE DAUPHINE',
 'PORTE DOREE',
 'PORTE MAILLOT',
 'PRE-ST-GERVAIS',
 'PTE CHAMPERRET',
 'PTE CHARENTON',
 "PTE D'AUTEUIL",
 "PTE D'ORLEANS",
 'PTE D. VINCENN',
 'PTE D.BAGNOLET',
 'PTE D.CHAPELLE',
 'PTE D.ST-OUEN',
 'PTE D.VILLETTE',
 'PTE DE CHOISY',
 'PTE DE CLICHY',
 'PTE DE PANTIN',
 'PTE MONTREUIL',
 'PTE ST-CLOUD',
 'PYRAMIDES',
 'PYRENEES',
 'QUAI D.LA GARE',
 'QUAI.LA RAPEE',
 'QUATRE-SEPTEMB',
 'RAMBUTEAU',
 'RANELAGH',
 'RASPAIL',
 'REAUMUR-SEB.',
 'RENNES',
 'REPUBLIQUE',
 'REUILLY-DID.',
 'RICHARD LENOIR',
 'RICHELIEU-DR.',
 'RIQUET',
 'ROBESPIERRE',
 'ROMAINV.CARNOT',
 'ROME',
 'ROSNY BOIS.P',
 'RUE D.LA POMPE',
 'RUE DU BAC',
 'S. GAINSBOURG',
 'SAINT-AMBROISE',
 'SAINT-AUGUSTIN',
 'SAINT-FARGEAU',
 'SAINT-GEORGES',
 'SAINT-JACQUES',
 'SAINT-LAZARE',
 'SAINT-MARCEL',
 'SAINT-MAUR',
 'SAINT-MICHEL',
 'SAINT-PAUL',
 'SAINT-PLACIDE',
 'SAINT-SULPICE',
 'SEGUR',
 'SENTIER',
 'SEVRES-BABYL.',
 'SEVRES-LECOUR.',
 'SIMPLON',
 'SOLFERINO',
 'ST-DENIS-BASIL',
 'ST-DENIS-PTE P',
 'ST-DENIS-UNIV.',
 'ST-FRAN.XAVIER',
 'ST-GERM.D.PRES',
 'ST-MANDE TOUR.',
 'ST-PH.DU-ROULE',
 'ST-SEBASTIEN.F',
 'STALINGRAD',
 'STRAS.ST-DENIS',
 'SULLY-MORLAND',
 'TELEGRAPHE',
 'TEMPLE',
 'TERNES',
 'THIAIS-ORLY',
 'TOLBIAC',
 'TRINITE',
 'TROCADERO',
 'TUILERIES',
 'VANEAU',
 'VARENNE',
 'VAUGIRARD',
 'VAVIN',
 'VICTOR HUGO',
 'VILLEJ.L.ARAG.',
 'VILLEJ.L.LAGR.',
 'VILLEJ.P.V.C',
 'VILLIERS',
 'VOLONTAIRES',
 'VOLTAIRE',
 'WAGRAM']

En comparant à la liste des stations de métro <https://fr.wikipedia.org/wiki/Liste_des_stations_du_m%C3%A9tro_de_Paris>, on note la présence de deux stations supplémentaires dans notre jeu de données :
- ANTONY : pourquoi ?
- FUNICULAIRE : on conserve cette station.

In [74]:
df[df["libelle_arret"] == "ANTONY"]

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald,id_zdc
4743,2025-09-24,100,110,19,ANTONY,NaN,Forfaits courts,2,69759.0
134536,2025-09-11,100,110,19,ANTONY,NaN,NON DEFINI,1,69759.0
146054,2025-09-10,100,110,19,ANTONY,NaN,Forfait Navigo,1,69759.0
150479,2025-09-22,100,110,19,ANTONY,NaN,Forfait Navigo,1,69759.0
175401,2025-09-29,100,110,19,ANTONY,NaN,Forfaits courts,1,69759.0
176491,2025-09-25,100,110,19,ANTONY,NaN,Forfaits courts,1,69759.0
274400,2025-09-11,100,110,19,ANTONY,NaN,Contrat Solidarité Transport,1,69759.0
39360,2025-11-19,100,110,19,ANTONY,NaN,Contrat Solidarite Transport,1,69759.0
55100,2025-11-07,100,110,19,ANTONY,NaN,Forfait Navigo,2,69759.0
119593,2025-11-19,100,110,19,ANTONY,NaN,Forfaits courts,6,69759.0
380424,2025-11-14,100,110,19,ANTONY,NaN,Forfait Navigo,2,69759.0
476232,2025-10-08,100,110,19,ANTONY,NaN,Forfait Navigo,1,69759.0

Au vu des très faibles effectifs, il s'agit vraisemblablement d'une erreur. On supprime ces occurrences :

In [75]:
df = df[df["libelle_arret"] != "ANTONY"]

On note également 4 stations manquantes :
- *Villejuif-Gustave-Roussy* : ouverte en janvier 2025 et non exploitée par la RATP,
- *Aéroport d'Orly* : tarification spécifique et non exploitée par la RATP,
- *Saint-Denis-Pleyel* : non exploitée par la RATP,
- *Cluny-La-Sorbonne* : *peut-être* du fait de sa liaison avec *Saint-Michel* ? Pas d'explicaton formelle.

## Colonne `categorie_titre`

In [76]:
pd.unique(df["categorie_titre"])

array(['Forfaits courts', 'Autres titres', 'Contrat Solidarité Transport',
       'Forfait Navigo', 'Imagine R', 'Amethyste', 'NON DEFINI',
       'Contrat Solidarite Transport'], dtype=object)

**On remarque la présence de "Contrat Solidarité Transport" *et* de "Contrat Solidarite Transport" ; on corrige ce dernier libellé :**

In [77]:
df = df.replace("Contrat Solidarite Transport", "Contrat Solidarité Transport")
pd.unique(df["categorie_titre"])

array(['Forfaits courts', 'Autres titres', 'Contrat Solidarité Transport',
       'Forfait Navigo', 'Imagine R', 'Amethyste', 'NON DEFINI'],
      dtype=object)

On calcule la proportion de `nb_valid` avec `categorie_titre` 'NON DEFINI' :

In [78]:
df[df["categorie_titre"] == "NON DEFINI"]["nb_vald"].sum() / df["nb_vald"].sum()

np.float64(0.010595519436082146)

On choisit de conserver cette modalité, bien que peu significative.

## Colonne `nb_vald`

Il s'agit de la seule colonne quantitative que nous allons étudier

In [79]:
df["nb_vald"].groupby(df["categorie_titre"]).describe()

,count,mean,std,min,25%,50%,75%,max
categorie_titre,,,,,,,,
Amethyste,114974.0,256.423000,229.219000,1.0,110.0,193.0,318.00,2693.0
Autres titres,114908.0,204.790250,394.783402,1.0,52.0,98.0,209.00,12481.0
Contrat Solidarité Transport,115102.0,1005.118304,1143.164582,1.0,374.0,666.0,1200.00,14491.0
Forfait Navigo,115454.0,5655.685234,5722.240091,1.0,2610.0,4333.0,6882.75,92195.0
Forfaits courts,115014.0,1917.825665,2674.105964,1.0,721.0,1163.0,1966.75,42157.0
Imagine R,115046.0,1758.261391,1716.595560,1.0,787.0,1350.0,2178.00,30768.0
NON DEFINI,115904.0,114.989146,129.726791,1.0,44.0,72.0,128.00,1400.0

**On remarque qu'il y a des valeurs inférieures à 5, contrairement à ce qui est spécifié dans la documentation du jeu de données.**

## Création du fichier source

### Suppression des colonnes inutiles

In [80]:
df = df.drop(
    ["code_stif_trns", "code_stif_res", "code_stif_arret", "ida", "id_zdc"], axis=1
)
df

             jour   libelle_arret               categorie_titre  nb_vald
0      2025-03-07       MADELEINE               Forfaits courts     3387
1      2025-03-07    BARBES-ROCH.                 Autres titres      478
2      2025-03-07   S. GAINSBOURG  Contrat Solidarité Transport      781
3      2025-03-07   S. GAINSBOURG                Forfait Navigo     2880
4      2025-03-07   S. GAINSBOURG                     Imagine R     1158
...           ...             ...                           ...      ...
480466 2025-10-04  VILLEJ.L.LAGR.                 Autres titres       49
480467 2025-10-04  VILLEJ.L.LAGR.  Contrat Solidarité Transport      591
480468 2025-10-04     VOLONTAIRES                 Autres titres       45
480469 2025-10-04     VOLONTAIRES  Contrat Solidarité Transport      226
480470 2025-10-04     VOLONTAIRES               Forfaits courts     1158

[806402 rows x 4 columns]

### Recherche de lignes doublonnées

Le jeu données ne devrait *théoriquement* plus comporter de **doublons (même jour, même arrêt, même catégorie de titre)**, mais il faut le verifier :

In [81]:
df_agr = df.groupby(["jour", "libelle_arret", "categorie_titre"])["nb_vald"].count()

doublons = df_agr[df_agr > 1]
doublons

jour        libelle_arret   categorie_titre
2025-01-01  MAIRIE ST-OUEN  Amethyste                       2
                            Autres titres                   2
                            Contrat Solidarité Transport    2
                            Forfait Navigo                  2
                            Forfaits courts                 2
                                                           ..
2025-12-31  PTE DE CLICHY   Contrat Solidarité Transport    2
                            Forfait Navigo                  2
                            Forfaits courts                 2
                            Imagine R                       2
                            NON DEFINI                      2
Name: nb_vald, Length: 5689, dtype: int64

On trouve un **grand nombre de doublons**, qu'il va falloir examminer :

In [82]:
doublons.sample(10)

jour        libelle_arret   categorie_titre
2025-10-20  MAIRIE ST-OUEN  Autres titres                   2
2025-03-05  MAIRIE ST-OUEN  Imagine R                       2
2025-06-25  MAIRIE ST-OUEN  Forfait Navigo                  2
2025-01-08  MAIRIE ST-OUEN  Autres titres                   2
2025-10-02  MAIRIE ST-OUEN  Imagine R                       2
2025-12-12  MAISON BLANCHE  Amethyste                       2
2025-02-17  MAISON BLANCHE  Forfait Navigo                  2
2025-08-16  MAISON BLANCHE  Forfait Navigo                  2
2025-03-28  MAISON BLANCHE  Imagine R                       2
2025-10-12  PTE DE CLICHY   Contrat Solidarité Transport    2
Name: nb_vald, dtype: int64

In [83]:
pd.unique(doublons.reset_index()["libelle_arret"])

array(['MAIRIE ST-OUEN', 'MAISON BLANCHE', 'PTE DE CLICHY'], dtype=object)

Ces doublons ne concernent donc que **trois stations**.

In [84]:
len(pd.unique(doublons.reset_index()["jour"]))

365

Mais ils s'étalent sur **toute l'année**.
On examine un échantillon de ces doublons, en faisant tourner plusieurs fois le code suivant :

In [85]:
# Échantillon du jeu de données sur 1 date aléatoire, pour les 3 stations présentant des doublons
df[
    (df["libelle_arret"].isin(pd.unique(doublons.reset_index()["libelle_arret"])))
    & (df["jour"].isin(df["jour"].sample(1)))
].sort_values(["jour", "libelle_arret", "categorie_titre"])

             jour   libelle_arret               categorie_titre  nb_vald
131032 2025-08-27  MAIRIE ST-OUEN                     Amethyste      214
264487 2025-08-27  MAIRIE ST-OUEN                     Amethyste      114
315498 2025-08-27  MAIRIE ST-OUEN                 Autres titres       22
445177 2025-08-27  MAIRIE ST-OUEN                 Autres titres       71
48841  2025-08-27  MAIRIE ST-OUEN  Contrat Solidarité Transport      626
445178 2025-08-27  MAIRIE ST-OUEN  Contrat Solidarité Transport     1855
131033 2025-08-27  MAIRIE ST-OUEN                Forfait Navigo     8261
445374 2025-08-27  MAIRIE ST-OUEN                Forfait Navigo     2447
48655  2025-08-27  MAIRIE ST-OUEN               Forfaits courts     1827
445375 2025-08-27  MAIRIE ST-OUEN               Forfaits courts      657
264488 2025-08-27  MAIRIE ST-OUEN                     Imagine R      453
315340 2025-08-27  MAIRIE ST-OUEN                     Imagine R     1646
264489 2025-08-27  MAIRIE ST-OUEN                    NON DEFINI       43
445179 2025-08-27  MAIRIE ST-OUEN                    NON DEFINI      127
48796  2025-08-27  MAISON BLANCHE                     Amethyste      291
264493 2025-08-27  MAISON BLANCHE                     Amethyste      111
315464 2025-08-27  MAISON BLANCHE                 Autres titres       83
315504 2025-08-27  MAISON BLANCHE                 Autres titres       35
48848  2025-08-27  MAISON BLANCHE  Contrat Solidarité Transport      381
445323 2025-08-27  MAISON BLANCHE  Contrat Solidarité Transport     1142
315465 2025-08-27  MAISON BLANCHE                Forfait Navigo     5685
315505 2025-08-27  MAISON BLANCHE                Forfait Navigo     2076
48849  2025-08-27  MAISON BLANCHE               Forfaits courts      545
131167 2025-08-27  MAISON BLANCHE               Forfaits courts     1373
48850  2025-08-27  MAISON BLANCHE                     Imagine R      623
445324 2025-08-27  MAISON BLANCHE                     Imagine R     1852
48797  2025-08-27  MAISON BLANCHE                    NON DEFINI      147
48851  2025-08-27  MAISON BLANCHE                    NON DEFINI       38
264584 2025-08-27   PTE DE CLICHY                     Amethyste      495
264585 2025-08-27   PTE DE CLICHY                 Autres titres      535
48927  2025-08-27   PTE DE CLICHY  Contrat Solidarité Transport     2682
445459 2025-08-27   PTE DE CLICHY                Forfait Navigo    11563
131300 2025-08-27   PTE DE CLICHY               Forfaits courts     2592
445460 2025-08-27   PTE DE CLICHY                     Imagine R     2595
264586 2025-08-27   PTE DE CLICHY                    NON DEFINI      195

**Conclusion : les lignes en doublon comportent des nombres de validations à la fois significatifs *et* différents. En l'absence d'explication, on décide de les *agréger par somme*.**

### Traitement par agrégation des lignes en doublon

In [86]:
# as_index=False : très important pour garder un jeu de données exportable proprement !
df = df.groupby(
    by=["jour", "libelle_arret", "categorie_titre"], as_index=False
).aggregate("sum")
df

             jour libelle_arret               categorie_titre  nb_vald
0      2025-01-01      ABBESSES                     Amethyste       18
1      2025-01-01      ABBESSES                 Autres titres     1042
2      2025-01-01      ABBESSES  Contrat Solidarité Transport       96
3      2025-01-01      ABBESSES                Forfait Navigo     1302
4      2025-01-01      ABBESSES               Forfaits courts     1059
...           ...           ...                           ...      ...
800708 2025-12-31        WAGRAM  Contrat Solidarité Transport      180
800709 2025-12-31        WAGRAM                Forfait Navigo     1517
800710 2025-12-31        WAGRAM               Forfaits courts      620
800711 2025-12-31        WAGRAM                     Imagine R      349
800712 2025-12-31        WAGRAM                    NON DEFINI       20

[800713 rows x 4 columns]

### Export du fichier des données traitées

Le fichier est exporté dans le répertoire parent de celui depuis lequel ce notebook est lancé. Selon l'arborescence du projet, cela correspond au **répertoire racine du projet**.

In [87]:
# durée : environ 1 min 30
df.to_excel("../data_traitee.xlsx", sheet_name="DATA", na_rep="NA", index=False)