---
title: Exploration préparatoire des données et génération du fichier source
---

In [116]:
import os

import s3fs
import pandas as pd
from numpy import datetime64, timedelta64

In [117]:
# Connexion au dépôt de données
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': "https://" + os.environ["AWS_S3_ENDPOINT"]})
# Récupération de la liste des fichiers
fichiers = fs.ls("jacquemmoz")

# Examen des fichiers

## Premier fichier

In [118]:
with fs.open(fichiers[0], mode="rb") as fichier:
    donnees1 = pd.read_excel(fichier)

In [119]:
donnees1.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
0,2025-03-07,100,110,487,MADELEINE,71324,Forfaits courts,3387
1,2025-03-07,100,110,49,BARBES-ROCH.,71426,Autres titres,478
2,2025-03-07,100,110,490763,S. GAINSBOURG,490779,Contrat Solidarité Transport,781
3,2025-03-07,100,110,490763,S. GAINSBOURG,490779,Forfait Navigo,2880
4,2025-03-07,100,110,490763,S. GAINSBOURG,490779,Imagine R,1158

In [120]:
donnees1.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
469371,2025-03-01,800,853,485,LUZARCHES,67177,Forfait Navigo,47
469372,2025-03-01,800,853,536,MERIEL,67065,Amethyste,2
469373,2025-03-01,800,853,536,MERIEL,67065,Imagine R,50
469374,2025-03-01,800,853,568,MONTSOULT,67000,Forfait Navigo,286
469375,2025-03-01,800,853,568,MONTSOULT,67000,Forfaits courts,57

In [121]:
donnees1.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
134360,2025-01-02,800,854,903,VILLENNES SEINE,64949,NON DEFINI,1
291158,2025-02-22,800,853,148,CHAPONVAL,67016,Imagine R,5
387175,2025-01-19,100,110,618,PALAIS-ROYAL,71297,Forfaits courts,4093
28101,2025-03-06,810,801,357,HOUILLES,64741,Forfaits courts,830
29992,2025-01-17,800,854,508,MANTES STATION,65770,NON DEFINI,30
57379,2025-01-11,100,110,864,TUILERIES,71284,Imagine R,843
347055,2025-03-23,100,110,490773,ROSNY BOIS.P,426280,Forfait Navigo,2586
46277,2025-02-17,800,854,111,BREVAL,65051,NON DEFINI,2
241505,2025-02-22,800,805,620,PANTIN,72421,Imagine R,524
140078,2025-01-16,100,110,11,ALEXANDR.DUMAS,71728,Autres titres,384

In [122]:
donnees1.dtypes

jour               object
code_stif_trns      int64
code_stif_res      object
code_stif_arret    object
libelle_arret      object
ida                 int64
categorie_titre    object
nb_vald             int64
dtype: object

> On voit d'ores et déjà qu'il faudra recoder la colonne 'jour' pour la transformer en type date.
La colonne nb_val est bien un entier.
Les autres colonnes seront utilisables telles quelles : soit on les utilisera comme chaînes de caractères, soit uniquement pour un premier tri des données avant suppression.

## Second fichier

In [123]:
with fs.open(fichiers[1], mode="rb") as fichier:
    donnees2 = pd.read_excel(fichier)
donnees2.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,id_zdc,categorie_titre,nb_vald
0,2025-04-12,100,110,861,TRINITE,71355.0,NON DEFINI,73
1,2025-04-12,100,110,862,TROCADERO,71285.0,Forfaits courts,12487
2,2025-04-12,100,110,862,TROCADERO,71285.0,Imagine R,3092
3,2025-04-12,100,110,864,TUILERIES,71284.0,Amethyste,56
4,2025-04-12,100,110,864,TUILERIES,71284.0,Contrat Solidarité Transport,267

In [124]:
donnees2.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,id_zdc,categorie_titre,nb_vald
474201,2025-06-03,800,803,367,ISSY VAL SEI,71016.0,NON DEFINI,67
474202,2025-06-03,800,803,369,IVRY SUR SEINE,424396.0,Forfaits courts,473
474203,2025-06-03,800,803,376,JAVEL,71150.0,Contrat Solidarité Transport,411
474204,2025-06-03,800,803,376,JAVEL,71150.0,Forfaits courts,1147
474205,2025-06-03,800,803,376,JAVEL,71150.0,Imagine R,1172

In [125]:
donnees2.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,id_zdc,categorie_titre,nb_vald
270449,2025-05-04,100,110,244,DUGOMMIER,71606.0,Autres titres,74
124603,2025-06-28,100,110,2,ABBESSES,71432.0,Forfaits courts,4606
402082,2025-05-15,800,850,572,MOUROUX,67944.0,Forfaits courts,21
247376,2025-05-03,100,110,548,MIROMESNIL,71346.0,Autres titres,117
345395,2025-04-26,100,110,98,BOULETS-MONTR.,71694.0,NON DEFINI,33
11874,2025-05-11,100,110,736,RICHARD LENOIR,73648.0,Imagine R,498
462928,2025-06-21,810,802,551,MITRY CLAYE,69065.0,Forfaits courts,488
78619,2025-04-23,100,110,90,BONNE NOUVELLE,71320.0,Forfait Navigo,7899
342501,2025-04-04,800,800,48090,Saint-Cyr T13,73731.0,Imagine R,21
190468,2025-04-20,810,801,578,NANTERRE-UNIV.,70956.0,NON DEFINI,115

In [126]:
donnees2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474206 entries, 0 to 474205
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   jour             474206 non-null  object
 1   code_stif_trns   474206 non-null  int64
 2   code_stif_res    474206 non-null  object
 3   code_stif_arret  474206 non-null  object
 4   libelle_arret    474206 non-null  object
 5   id_zdc           473185 non-null  float64
 6   categorie_titre  474206 non-null  object
 7   nb_vald          474206 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 28.9+ MB

## Troisième fichier

In [127]:
with fs.open(fichiers[2], mode="rb") as fichier:
    donnees3 = pd.read_excel(fichier)
donnees3.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
0,2025-09-21,810,801,393,71517.0,LA DEFENSE,Forfaits courts,7732
1,2025-09-21,810,801,431,70359.0,LE PARC S.MAUR,NON DEFINI,47
2,2025-09-21,810,801,438,64514.0,LE VESINET-CEN,Autres titres,10
3,2025-09-21,810,801,473,68123.0,LOGNES,Imagine R,521
4,2025-09-21,810,801,473,68123.0,LOGNES,NON DEFINI,28

In [128]:
donnees3.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
468221,2025-09-21,800,803,26,60072.0,ARPAJON,Forfait Navigo,314
468222,2025-09-21,800,803,3,69554.0,ABLON,Contrat Solidarité Transport,134
468223,2025-09-21,800,803,31,63134.0,ATHIS MONS,Forfait Navigo,244
468224,2025-09-21,800,803,326,72303.0,GENNEVILLIERS,Forfaits courts,156
468225,2025-09-21,800,803,326,72303.0,GENNEVILLIERS,Imagine R,223

In [129]:
donnees3.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
391902,2025-09-12,100,110,519,71510.0,MARX DORMOY,Amethyste,332
91326,2025-09-20,100,110,652,71033.0,PLACE D'ITALIE,Forfait Navigo,14965
44049,2025-09-01,100,110,716,71864.0,PYRENEES,NON DEFINI,35
236230,2025-07-04,800,800,48094,64566.0,Bel Air - Fourqueux T13,Contrat Solidarité Transport,106
362106,2025-07-10,800,852,906,64145.0,VILLEPREUX,Contrat Solidarité Transport,208
248941,2025-08-24,100,110,729,71311.0,REPUBLIQUE,Forfait Navigo,8535
449753,2025-08-29,800,800,48092,64622.0,Lisière Pereire T13,NON DEFINI,2
32066,2025-07-17,100,110,583,71673.0,NATION,Imagine R,2857
351983,2025-09-16,100,110,1017,73848.0,FUNICULAIRE,Forfait Navigo,2537
164932,2025-08-03,800,822,1233,68505.0,COUILLY ST G T14,Forfait Navigo,17

In [130]:
donnees3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468226 entries, 0 to 468225
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   jour             468226 non-null  object
 1   code_stif_trns   468226 non-null  int64
 2   code_stif_res    468226 non-null  object
 3   code_stif_arret  468226 non-null  object
 4   id_zdc           467625 non-null  float64
 5   libelle_arret    468226 non-null  object
 6   categorie_titre  468226 non-null  object
 7   nb_vald          468226 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 28.6+ MB

## Quatrième fichier

In [131]:
with fs.open(fichiers[3], mode="rb") as fichier:
    donnees4 = pd.read_excel(fichier)
donnees4.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
0,2025-10-31,800,803,454,69662,SAULES,Autres titres,1
1,2025-10-31,800,803,454,69662,SAULES,Forfaits courts,188
2,2025-10-31,800,803,788,60987,SAVIGNY SUR ORG,Imagine R,1263
3,2025-10-31,800,803,793,59842,SERMAISE,Amethyste,1
4,2025-10-31,800,803,793,59842,SERMAISE,Forfait Navigo,42

In [132]:
donnees4.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
147480,2025-11-08,800,851,158,61763,CHARTRETTES,Contrat Solidarite Transport,2
315856,2025-12-12,800,803,611,69639,ORLY VILLE,Forfait Navigo,1288
55796,2025-11-07,800,852,911,424296,VILLIERS NEAUPH,Forfaits courts,101
279793,2025-10-28,800,853,470,67172,ISLE ADAM,Contrat Solidarite Transport,80
265706,2025-12-19,810,802,484,71161,LUXEMBOURG,Forfaits courts,2744
274925,2025-12-05,100,110,725,73636,REAUMUR-SEB.,Imagine R,3274
347259,2025-11-28,100,110,251,71166,EGLI.D'AUTEUIL,Amethyste,4
96345,2025-10-07,100,110,21,71419,ANVERS,NON DEFINI,260
214818,2025-10-19,800,804,482,69300,LOUVRES,Forfaits courts,142
135430,2025-12-19,100,110,625,71801,PARMENTIER,Forfait Navigo,5149

In [133]:
donnees4.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
480640,2025-10-04,800,852,797,463754,SEVRES RG,Forfait Navigo,657
480641,2025-10-04,800,852,813,73731,ST CYR,Contrat Solidarite Transport,217
480642,2025-10-04,800,852,938,63812,ST QUENTIN YVE,Amethyste,131
480643,2025-10-04,800,852,938,63812,ST QUENTIN YVE,Imagine R,1660
480644,2025-10-04,800,852,846,64194,TACOIGNIERES,Amethyste,1

In [134]:

donnees4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480645 entries, 0 to 480644
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   jour             480645 non-null  object
 1   code_stif_trns   480645 non-null  int64
 2   code_stif_res    480645 non-null  object
 3   code_stif_arret  480645 non-null  object
 4   id_zdc           480645 non-null  int64
 5   libelle_arret    480645 non-null  object
 6   categorie_titre  480645 non-null  object
 7   nb_vald          480645 non-null  int64
dtypes: int64(3), object(5)
memory usage: 29.3+ MB

# Concaténation des quatre fichiers en un dataframe Pandas

On utilise les dataframes issus de l'examen des fichiers dans la partie précédente. C'est pour cela qu'on n'a pas recours à une boucle `for`.

In [135]:
df = pd.concat((donnees1, donnees2, donnees3, donnees4))
# vérification de la longueur du dataframe concaténé
len(df) == len(donnees1) + len(donnees2) + len(donnees3) + len(donnees4)

True

In [136]:
df.sample(15)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald,id_zdc
297803,2025-02-28,100,110,159,CHATEAU D'EAU,71333.0,Forfait Navigo,6280,NaN
433382,2025-07-27,810,801,202,CONFLANS FO,NaN,Amethyste,25,73605.0
378476,2025-04-05,800,803,756,RUNGIS,NaN,Forfait Navigo,98,69633.0
215576,2025-10-23,800,850,472,LIZY SUR OURCQ,NaN,NON DEFINI,1,69237.0
131322,2025-01-11,100,110,99,BOULOGNE-J.J.,71147.0,Forfaits courts,1032,NaN
271661,2025-05-05,100,110,718,QUAI.LA RAPEE,NaN,Amethyste,60,71637.0
253141,2025-01-21,100,110,93,BOTZARIS,71906.0,Amethyste,81,NaN
301467,2025-09-08,100,110,490834,THIAIS-ORLY,NaN,Imagine R,540,69677.0
139072,2025-01-15,100,110,223,CRETEIL-ECHAT,70269.0,Autres titres,312,NaN
13654,2025-07-08,810,802,827,SAINT-MICHEL,NaN,Autres titres,432,73620.0
274423,2025-11-19,100,110,490840,HOP. BICETRE,NaN,Forfaits courts,1223,70445.0
42569,2025-10-27,100,110,228,CRX.DE CHAVAUX,NaN,Amethyste,278,71756.0
20812,2025-11-28,800,805,178,CHELLES GOURNAY,NaN,NON DEFINI,16,68407.0
198445,2025-04-22,800,854,1210,PARC DU CHAT T12,NaN,Contrat Solidarité Transport,68,60892.0
49978,2025-01-29,100,110,758,SAINT-AMBROISE,71781.0,Amethyste,246,NaN

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1892453 entries, 0 to 480644
Data columns (total 9 columns):
 #   Column           Dtype
---  ------           -----
 0   jour             object
 1   code_stif_trns   int64
 2   code_stif_res    object
 3   code_stif_arret  object
 4   libelle_arret    object
 5   ida              float64
 6   categorie_titre  object
 7   nb_vald          int64
 8   id_zdc           float64
dtypes: float64(2), int64(2), object(5)
memory usage: 144.4+ MB

On va prendre chaque colonne, la mettre en forme le cas échéant, vérifier sa conformité.

## Colonne `jour`
On convertit cette colonne en type `date`, puis on vérifie que chaque jour de l'année 2025 est bien présent (comparaison au set `annee`de l'ensemble des jours de 2025).

In [138]:
df["jour"] = pd.to_datetime(df["jour"])
annee = {datetime64("2025-01-01") + timedelta64(i) for i in range(365)}
print(set(df["jour"]) == annee)    # pd.unique(df["jour"]) peut calculer plus vite
                                    # ou annee.difference(set(df["jour"]))

True

## Colone `code_stif_trns`

Il s'agit du code du transporteur. Seule la RATP, code 100 nous intéresse.

In [139]:
pd.unique(df['code_stif_trns'])

array([100, 760, 762, 800, 810, 761, 764])

In [140]:
df = df[df['code_stif_trns'] == 100]

## Colonne `code_stif_res`

Il s'agit du code du réseau. Seul le code 110, correspondant au métro, nous intéresse.

In [141]:
pd.unique(df['code_stif_res'])

array(['110', 'ND'], dtype=object)

On doit éliminer les données du réseau 'ND'. Cependant on regarde avant la proportion de `nb_vald` (la variable quantitative que l'on va étudier) que cela représente.

In [142]:
df[df['code_stif_res']=='ND']['nb_vald'].sum()/df['nb_vald'].sum()

np.float64(0.000417352438591083)

Ce nombre est négligeable.

In [143]:
df = df[df['code_stif_res']=='110']

## Colonne `categorie_titre`

In [144]:
pd.unique(df['categorie_titre'])

array(['Forfaits courts', 'Autres titres', 'Contrat Solidarité Transport',
       'Forfait Navigo', 'Imagine R', 'Amethyste', 'NON DEFINI',
       'Contrat Solidarite Transport'], dtype=object)

> **On remarque la présente de 'Contrat Solidarité Transport' et 'Contrat Solidarite Transport' ; on corrige de dernier libellé :**

In [145]:
df = df.replace("Contrat Solidarite Transport", "Contrat Solidarité Transport")
pd.unique(df['categorie_titre'])

array(['Forfaits courts', 'Autres titres', 'Contrat Solidarité Transport',
       'Forfait Navigo', 'Imagine R', 'Amethyste', 'NON DEFINI'],
      dtype=object)

On calcule la proportion de `nb_valid` avec `categorie_titre` 'NON DEFINI' :

In [146]:
df[df['categorie_titre']=='NON DEFINI']['nb_vald'].sum()/df['nb_vald'].sum()

np.float64(0.01059552006261316)

## Colonne `nb_vald`

Il s'agit de la seule colonne quantitative que nous allons étudier

In [147]:
df['nb_vald'].groupby(df['categorie_titre']).describe()

,count,mean,std,min,25%,50%,75%,max
categorie_titre,,,,,,,,
Amethyste,114974.0,256.423000,229.219000,1.0,110.0,193.0,318.0,2693.0
Autres titres,114908.0,204.790250,394.783402,1.0,52.0,98.0,209.0,12481.0
Contrat Solidarité Transport,115104.0,1005.100857,1143.162313,1.0,374.0,666.0,1200.0,14491.0
Forfait Navigo,115459.0,5655.440373,5722.237160,1.0,2610.0,4333.0,6882.0,92195.0
Forfaits courts,115018.0,1917.759055,2674.083318,1.0,721.0,1163.0,1966.0,42157.0
Imagine R,115046.0,1758.261391,1716.595560,1.0,787.0,1350.0,2178.0,30768.0
NON DEFINI,115905.0,114.988163,129.726663,1.0,44.0,72.0,128.0,1400.0

## Création du fichier source

### Suppression des colonnes inutiles

In [148]:
df = df.drop(['code_stif_trns', 'code_stif_res', 'code_stif_arret', 'ida', 'id_zdc'], axis=1)
df

             jour   libelle_arret               categorie_titre  nb_vald
0      2025-03-07       MADELEINE               Forfaits courts     3387
1      2025-03-07    BARBES-ROCH.                 Autres titres      478
2      2025-03-07   S. GAINSBOURG  Contrat Solidarité Transport      781
3      2025-03-07   S. GAINSBOURG                Forfait Navigo     2880
4      2025-03-07   S. GAINSBOURG                     Imagine R     1158
...           ...             ...                           ...      ...
480466 2025-10-04  VILLEJ.L.LAGR.                 Autres titres       49
480467 2025-10-04  VILLEJ.L.LAGR.  Contrat Solidarité Transport      591
480468 2025-10-04     VOLONTAIRES                 Autres titres       45
480469 2025-10-04     VOLONTAIRES  Contrat Solidarité Transport      226
480470 2025-10-04     VOLONTAIRES               Forfaits courts     1158

[806414 rows x 4 columns]

### Agrégation des lignes

In [149]:
# as_index=False : très important pour garder un exportable proprement !
df = df.groupby(by=['jour', 'libelle_arret', 'categorie_titre'], as_index=False).aggregate("sum")
df

             jour libelle_arret               categorie_titre  nb_vald
0      2025-01-01      ABBESSES                     Amethyste       18
1      2025-01-01      ABBESSES                 Autres titres     1042
2      2025-01-01      ABBESSES  Contrat Solidarité Transport       96
3      2025-01-01      ABBESSES                Forfait Navigo     1302
4      2025-01-01      ABBESSES               Forfaits courts     1059
...           ...           ...                           ...      ...
800720 2025-12-31        WAGRAM  Contrat Solidarité Transport      180
800721 2025-12-31        WAGRAM                Forfait Navigo     1517
800722 2025-12-31        WAGRAM               Forfaits courts      620
800723 2025-12-31        WAGRAM                     Imagine R      349
800724 2025-12-31        WAGRAM                    NON DEFINI       20

[800725 rows x 4 columns]

In [150]:
sorted(pd.unique(df['libelle_arret']))

['ABBESSES',
 'AIME CESAIRE',
 'ALESIA',
 'ALEXANDR.DUMAS',
 'ALFORT-ECOLE V',
 'ALMA-MARCEAU',
 'ANATOLE FRANCE',
 'ANTONY',
 'ANVERS',
 'ARGENTINE',
 'ARTS.METIERS',
 'ASSEMBLEE NAT.',
 'AUBERV.4 CHEM.',
 'AV.EMILE ZOLA',
 'AVRON',
 'BALARD',
 'BARBARA',
 'BARBES-ROCH.',
 'BASTILLE',
 'BEL AIR',
 'BELLEVILLE',
 'BERAULT',
 'BERCY',
 'BIBLIOTHEQUE',
 'BILLANCOURT',
 'BIR-HAKEIM',
 'BLANCHE',
 'BOB.P.PICASSO',
 'BOB.R.QUENEAU',
 'BOISSIERE',
 'BOLIVAR',
 'BONNE NOUVELLE',
 'BOTZARIS',
 'BOUCICAUT',
 'BOULETS-MONTR.',
 'BOULOGNE-J.J.',
 'BOULOGNE-ST.CL',
 'BOURSE',
 'BREGUET-SABIN',
 'BROCHANT',
 'BUTTES-CHAUM.',
 'BUZENVAL',
 'CADET',
 'CAMBRONNE',
 'CAMPO-FORMIO',
 'CARD.LEMOINE',
 'CARREF.PLEYEL',
 'CENSIER DAUB.',
 'CH.D.G.ETOILE',
 'CH.D.VINCENNES',
 'CHAMPS-ELYSEES',
 'CHARDON-LAGACH',
 'CHARENTON-ECO.',
 'CHARL.MICHELS',
 'CHARONNE',
 "CHATEAU D'EAU",
 'CHATEAU ROUGE',
 'CHATEAU-LANDON',
 'CHATELET',
 'CHATILLON-MON.',
 "CHAUSS.D'ANTIN",
 'CHEMIN-VERT',
 'CHEVALERET',
 'CHEVILLY-LARUE',
 'CITE',
 'CLICHY ST-OUEN',
 'COLONEL FABIEN',
 'COMMERCE',
 'CONCORDE',
 'CONVENTION',
 'CORENT.CARIOU',
 'CORENT.CELTON',
 'CORVISART',
 'COT. BEAUCLAIR',
 'COUR ST-EMILI.',
 'COURCELLES',
 'COURONNES',
 'CRETEIL-ECHAT',
 'CRETEIL-P. LAC',
 'CRETEIL-PREF.',
 'CRETEIL-UNIV.',
 'CRIMEE',
 'CRX.DE CHAVAUX',
 'DANUBE',
 'DAUMESNIL',
 'DENFERT-ROCH.',
 'DUGOMMIER',
 'DUPLEIX',
 'DUROC',
 'EC.MILITAIRE',
 'EDGAR QUINET',
 "EGLI.D'AUTEUIL",
 'EGLI.DE PANTIN',
 'ESPLANADE DEF.',
 'ETIENNE MARCEL',
 'EUROPE',
 'EXELMANS',
 'F.D.ROOSEVELT',
 'FAIDHERBE-CHA.',
 'FALGUIERE',
 'FELIX FAURE',
 'FILLES DU CALV',
 "FORT D'AUBERV.",
 'FR. POPULAIRE',
 'FUNICULAIRE',
 'GABRIEL PERI',
 'GAITE',
 'GALLIENI',
 'GAMBETTA',
 "GARE D'AUSTER.",
 "GARE DE L'EST",
 'GARE DE LYON',
 'GARE DU NORD',
 'GARIBALDI',
 'GDS BOULEVARDS',
 'GEORGE V',
 'GLACIERE',
 'GONCOURT',
 'GUY MOQUET',
 'HAVR.CAUMARTIN',
 'HOCHE',
 'HOP. BICETRE',
 'HOTEL DE VILLE',
 'IENA',
 'INVALIDES',
 'J.BONSERGENT',
 'JASMIN',
 'JAURES',
 'JAVEL',
 'JOURDAIN',
 'JULES JOFFRIN',
 'JUSSIEU',
 'KLEBER',
 'KREML.BICETRE',
 "L'HAY-LES-ROSE",
 'LA CHAPELLE',
 'LA COURNEUVE',
 'LA DEFENSE',
 'LA DHUYS',
 'LA FOURCHE',
 'LA MOTTE-PICQ.',
 'LA MUETTE',
 'LAMARCK-CAUL.',
 'LATOUR-MAUB.',
 'LAUMIERE',
 'LE PELETIER',
 'LEDRU-ROLLIN',
 'LES AGNETTES',
 'LES COURTILLES',
 'LES GOBELINS',
 'LES HALLES',
 'LES SABLONS',
 'LIBERTE',
 'LIEGE',
 'LOUIS BLANC',
 'LOUISE MICHEL',
 'LOURMEL',
 'LOUVRE',
 'LUCIE AUBRAC',
 'M. MONTROUGE',
 'M.ANGE-AUTEUIL',
 'M.ANGE-MOLITOR',
 'MABILLON',
 'MADELEINE',
 'MAIRIE CLICHY',
 "MAIRIE D'AUBERVILLIERS",
 "MAIRIE D'ISSY",
 "MAIRIE D'IVRY",
 'MAIRIE D.LILAS',
 'MAIRIE D.MONT',
 'MAIRIE ST-OUEN',
 'MAIS.ALF-JUIL.',
 'MAIS.ALF-STADE',
 'MAISON BLANCHE',
 'MALAK-P.VANVES',
 'MALAK.ET.DOLET',
 'MALESHERBES',
 'MARAICHERS',
 'MARCADET-POIS.',
 'MARCEL SEMBAT',
 'MARX DORMOY',
 'MAUBERT-MUTUA.',
 'MENILMONTANT',
 'MICHEL BIZOT',
 'MIRABEAU',
 'MIROMESNIL',
 'MONCEAU',
 'MONTGALLET',
 'MONTPARNASSE',
 'MONTREUIL HOP.',
 'MOUTON-DUVERN.',
 'N.D.DE-LORETTE',
 'N.D.DES-CHAMPS',
 'NATION',
 'NATIONALE',
 'OBERKAMPF',
 'ODEON',
 'OLYMPIADES',
 'OPERA',
 'OURCQ',
 'PALAIS-ROYAL',
 'PARMENTIER',
 'PASSY',
 'PASTEUR',
 'PELLEPORT',
 'PERE-LACHAISE',
 'PEREIRE',
 'PERNETY',
 'PHIL.AUGUSTE',
 'PICPUS',
 'PIERRE CURIE',
 'PIGALLE',
 'PLACE CLICHY',
 "PLACE D'ITALIE",
 'PLACE D. FETES',
 'PLACE MONGE',
 'PLAISANCE',
 'POISSONNIERE',
 'PONT CARDINET',
 'PONT D.NEUILLY',
 'PONT DE SEVRES',
 'PONT LEVALLOIS',
 'PONT MARIE',
 'PONT-NEUF',
 "PORTE D'ITALIE",
 "PORTE D'IVRY",
 'PORTE D.CLIGN.',
 'PORTE D.LILAS',
 'PORTE D.VANVES',
 'PORTE D.VERS.',
 'PORTE DAUPHINE',
 'PORTE DOREE',
 'PORTE MAILLOT',
 'PRE-ST-GERVAIS',
 'PTE CHAMPERRET',
 'PTE CHARENTON',
 "PTE D'AUTEUIL",
 "PTE D'ORLEANS",
 'PTE D. VINCENN',
 'PTE D.BAGNOLET',
 'PTE D.CHAPELLE',
 'PTE D.ST-OUEN',
 'PTE D.VILLETTE',
 'PTE DE CHOISY',
 'PTE DE CLICHY',
 'PTE DE PANTIN',
 'PTE MONTREUIL',
 'PTE ST-CLOUD',
 'PYRAMIDES',
 'PYRENEES',
 'QUAI D.LA GARE',
 'QUAI.LA RAPEE',
 'QUATRE-SEPTEMB',
 'RAMBUTEAU',
 'RANELAGH',
 'RASPAIL',
 'REAUMUR-SEB.',
 'RENNES',
 'REPUBLIQUE',
 'REUILLY-DID.',
 'RICHARD LENOIR',
 'RICHELIEU-DR.',
 'RIQUET',
 'ROBESPIERRE',
 'ROMAINV.CARNOT',
 'ROME',
 'ROSNY BOIS.P',
 'RUE D.LA POMPE',
 'RUE DU BAC',
 'S. GAINSBOURG',
 'SAINT-AMBROISE',
 'SAINT-AUGUSTIN',
 'SAINT-FARGEAU',
 'SAINT-GEORGES',
 'SAINT-JACQUES',
 'SAINT-LAZARE',
 'SAINT-MARCEL',
 'SAINT-MAUR',
 'SAINT-MICHEL',
 'SAINT-PAUL',
 'SAINT-PLACIDE',
 'SAINT-SULPICE',
 'SEGUR',
 'SENTIER',
 'SEVRES-BABYL.',
 'SEVRES-LECOUR.',
 'SIMPLON',
 'SOLFERINO',
 'ST-DENIS-BASIL',
 'ST-DENIS-PTE P',
 'ST-DENIS-UNIV.',
 'ST-FRAN.XAVIER',
 'ST-GERM.D.PRES',
 'ST-MANDE TOUR.',
 'ST-PH.DU-ROULE',
 'ST-SEBASTIEN.F',
 'STALINGRAD',
 'STRAS.ST-DENIS',
 'SULLY-MORLAND',
 'TELEGRAPHE',
 'TEMPLE',
 'TERNES',
 'THIAIS-ORLY',
 'TOLBIAC',
 'TRINITE',
 'TROCADERO',
 'TUILERIES',
 'VANEAU',
 'VARENNE',
 'VAUGIRARD',
 'VAVIN',
 'VICTOR HUGO',
 'VILLEJ.L.ARAG.',
 'VILLEJ.L.LAGR.',
 'VILLEJ.P.V.C',
 'VILLIERS',
 'VOLONTAIRES',
 'VOLTAIRE',
 'WAGRAM']

En comparant à lal liste des stations de métro <https://fr.wikipedia.org/wiki/Liste_des_stations_du_m%C3%A9tro_de_Paris>, on note la présence de deux stations supplémentaires dans notre jeu de données :
- ANTONY : pourquoi ?
- FUNICULAIRE : on conserve cette station.

In [151]:
df[df['libelle_arret'] == 'ANTONY']

             jour libelle_arret               categorie_titre  nb_vald
551113 2025-09-10        ANTONY                Forfait Navigo        1
553326 2025-09-11        ANTONY  Contrat Solidarité Transport        1
553327 2025-09-11        ANTONY                    NON DEFINI        1
577367 2025-09-22        ANTONY                Forfait Navigo        1
581784 2025-09-24        ANTONY               Forfaits courts        2
583990 2025-09-25        ANTONY               Forfaits courts        1
592839 2025-09-29        ANTONY               Forfaits courts        1
612810 2025-10-08        ANTONY                Forfait Navigo        1
678882 2025-11-07        ANTONY                Forfait Navigo        2
694164 2025-11-14        ANTONY                Forfait Navigo        2
705162 2025-11-19        ANTONY  Contrat Solidarité Transport        1
705163 2025-11-19        ANTONY               Forfaits courts        6

Au vu des très faibles effectifs, il s'agit vraisemblablement d'une erreur. On supprime ces occurrences :

In [152]:
df = df[df['libelle_arret'] != "ANTONY"]

On note également 4 stations manquantes :
- *Villejuif-Gustave-Roussy* : ouverte en janvier 2025 et non exploitée par la RATP,
- *Aéroport d'Orly* : tarification spécifique et non exploitée par la RATP,
- *Saint-Denis-Pleyel* : non exploitée par la RATP,
- *Cluny-La-Sorbonne* : *peut-être* du fait de sa liaison avec *Saint-Michel* ? Pas d'explicaton formelle.

## Export du fichier source

In [153]:
# 1m 32.6s
df.to_excel("s3://jacquemmoz/data_traitee.xlsx", sheet_name="DATA", na_rep="NA", index=False)