---
title: Exploration préparatoire des données et génération du fichier de données traitées
---

(Les fichiers téléchargés sont stockés ici :
- https://minio.lab.sspcloud.fr/jacquemmoz/partage/validations-reseau-ferre-nombre-validations-par-jour-1er-trimestre.xlsx
- https://minio.lab.sspcloud.fr/jacquemmoz/partage/validations-reseau-ferre-nombre-validations-par-jour-2eme-trimestre.xlsx
- https://minio.lab.sspcloud.fr/jacquemmoz/partage/validations-reseau-ferre-nombre-validations-par-jour-3eme-trimestre.xlsx
- https://minio.lab.sspcloud.fr/jacquemmoz/partage/validations-reseau-ferre-nombre-validations-par-jour-4eme-trimestre.xls
)

In [1]:
import pandas as pd
from numpy import datetime64, timedelta64

In [2]:
# Les fichiers partagés sur le service S3 d'Onyxia ont donc une URL de la forme :
fichier = "https://minio.lab.sspcloud.fr/jacquemmoz/partage/validations-reseau-ferre-nombre-validations-par-jour-{}-trimestre.xlsx"

# Examen des fichiers

## Premier fichier

In [3]:
# durée : environ 1 min
donnees1 = pd.read_excel(fichier.format("1er"))

In [4]:
donnees1.head()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
0,2025-03-07,100,110,487,MADELEINE,71324,Forfaits courts,3387
1,2025-03-07,100,110,49,BARBES-ROCH.,71426,Autres titres,478
2,2025-03-07,100,110,490763,S. GAINSBOURG,490779,Contrat Solidarité Transport,781
3,2025-03-07,100,110,490763,S. GAINSBOURG,490779,Forfait Navigo,2880
4,2025-03-07,100,110,490763,S. GAINSBOURG,490779,Imagine R,1158

In [5]:
donnees1.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
469371,2025-03-01,800,853,485,LUZARCHES,67177,Forfait Navigo,47
469372,2025-03-01,800,853,536,MERIEL,67065,Amethyste,2
469373,2025-03-01,800,853,536,MERIEL,67065,Imagine R,50
469374,2025-03-01,800,853,568,MONTSOULT,67000,Forfait Navigo,286
469375,2025-03-01,800,853,568,MONTSOULT,67000,Forfaits courts,57

In [6]:
donnees1.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald
274435,2025-03-30,100,110,877,VAUGIRARD,71091,NON DEFINI,61
279798,2025-03-20,100,110,772,ST-MANDE TOUR.,71647,Autres titres,432
350267,2025-03-26,100,110,555,MONTGALLET,71631,Autres titres,106
113833,2025-02-14,100,110,409,LA CHAPELLE,74000,Autres titres,242
286688,2025-02-20,100,110,836,STRAS.ST-DENIS,73633,Amethyste,721
395575,2025-02-10,800,850,711,PROVINS,62139,Forfait Navigo,337
207884,2025-03-10,800,805,446,BOULLEREAUX,73098,Autres titres,9
218094,2025-01-02,800,852,325,GAZERAN,60454,Forfaits courts,11
213286,2025-01-13,100,110,84,BOISSIERE,71301,Forfait Navigo,4115
113744,2025-02-14,100,110,210,CORENT.CELTON,70990,NON DEFINI,40

In [7]:
donnees1.dtypes

jour               object
code_stif_trns      int64
code_stif_res      object
code_stif_arret    object
libelle_arret      object
ida                 int64
categorie_titre    object
nb_vald             int64
dtype: object

> On voit d'ores et déjà qu'il faudra recoder la colonne 'jour' pour la transformer en type date.
La colonne nb_val est bien un entier.
Les autres colonnes seront utilisables telles quelles : soit on les utilisera comme chaînes de caractères, soit uniquement pour un premier tri des données avant suppression.

## Deuxième fichier

In [8]:
donnees2 = pd.read_excel(fichier.format("2eme"))

In [9]:
donnees2.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,id_zdc,categorie_titre,nb_vald
474201,2025-06-03,800,803,367,ISSY VAL SEI,71016.0,NON DEFINI,67
474202,2025-06-03,800,803,369,IVRY SUR SEINE,424396.0,Forfaits courts,473
474203,2025-06-03,800,803,376,JAVEL,71150.0,Contrat Solidarité Transport,411
474204,2025-06-03,800,803,376,JAVEL,71150.0,Forfaits courts,1147
474205,2025-06-03,800,803,376,JAVEL,71150.0,Imagine R,1172

In [10]:
donnees2.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,id_zdc,categorie_titre,nb_vald
93622,2025-06-27,810,801,753,RUEIL-MALMAIS.,70902.0,Forfaits courts,2742
14549,2025-05-23,100,110,72,BIBLIOTHEQUE,71572.0,Amethyste,455
307212,2025-04-22,810,802,796,SEVRAN LIVRY,73439.0,Imagine R,954
405136,2025-05-04,810,802,551,MITRY CLAYE,69065.0,NON DEFINI,60
322771,2025-06-01,100,110,497,MAISON BLANCHE,70645.0,Forfait Navigo,1278
288974,2025-05-28,800,852,325,GAZERAN,60454.0,Amethyste,2
391005,2025-06-16,100,110,98,BOULETS-MONTR.,71694.0,Amethyste,225
330954,2025-05-03,800,803,274,ETRECHY,59678.0,Contrat Solidarité Transport,32
441201,2025-05-20,800,805,968,YVRIS NOISY GD,73096.0,Amethyste,10
288518,2025-05-14,810,802,616,PALAISEAU,63175.0,Imagine R,650

In [11]:
donnees2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 474206 entries, 0 to 474205
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   jour             474206 non-null  object
 1   code_stif_trns   474206 non-null  int64
 2   code_stif_res    474206 non-null  object
 3   code_stif_arret  474206 non-null  object
 4   libelle_arret    474206 non-null  object
 5   id_zdc           473185 non-null  float64
 6   categorie_titre  474206 non-null  object
 7   nb_vald          474206 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 28.9+ MB

## Troisième fichier

In [12]:
donnees3 = pd.read_excel(fichier.format("3eme"))

In [13]:
donnees3.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
468221,2025-09-21,800,803,26,60072.0,ARPAJON,Forfait Navigo,314
468222,2025-09-21,800,803,3,69554.0,ABLON,Contrat Solidarité Transport,134
468223,2025-09-21,800,803,31,63134.0,ATHIS MONS,Forfait Navigo,244
468224,2025-09-21,800,803,326,72303.0,GENNEVILLIERS,Forfaits courts,156
468225,2025-09-21,800,803,326,72303.0,GENNEVILLIERS,Imagine R,223

In [14]:
donnees3.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
135523,2025-09-07,800,852,62,69528.0,BELLEVUE,Amethyste,6
56933,2025-08-25,800,800,1204,72787.0,PIERREFITTE T11,Contrat Solidarité Transport,626
246414,2025-08-23,800,854,579,70956.0,NANTERRE UNIVER,NON DEFINI,3
305806,2025-09-11,810,802,520,63244.0,MASSY-PALAIS.,Autres titres,40
63253,2025-08-11,800,804,196,62558.0,COMBS LA VILLE,Amethyste,71
466826,2025-09-19,100,110,772,71647.0,ST-MANDE TOUR.,Forfaits courts,2902
74825,2025-08-09,100,110,614,71972.0,OURCQ,Forfaits courts,999
44958,2025-09-02,100,110,419,71492.0,LAMARCK-CAUL.,Imagine R,828
212438,2025-08-11,800,853,961,66659.0,ST OUEN LIESSE,Forfait Navigo,832
322325,2025-08-22,100,110,250,71108.0,EDGAR QUINET,Forfaits courts,877

In [15]:
donnees3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468226 entries, 0 to 468225
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   jour             468226 non-null  object
 1   code_stif_trns   468226 non-null  int64
 2   code_stif_res    468226 non-null  object
 3   code_stif_arret  468226 non-null  object
 4   id_zdc           467625 non-null  float64
 5   libelle_arret    468226 non-null  object
 6   categorie_titre  468226 non-null  object
 7   nb_vald          468226 non-null  int64
dtypes: float64(1), int64(2), object(5)
memory usage: 28.6+ MB

## Quatrième fichier

In [16]:
donnees4 = pd.read_excel(fichier.format("4eme"))

In [17]:
donnees4.sample(10)

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
265001,2025-12-19,100,110,250,71108,EDGAR QUINET,Forfaits courts,1389
457399,2025-10-27,810,801,826,70393,ST-MAUR-CRET.,Forfait Navigo,6770
194295,2025-10-05,810,802,839,62978,ST-REMY-LES-CH,Imagine R,191
10677,2025-10-09,800,854,304,70713,GARCHES MARNES,Autres titres,15
33527,2025-11-12,100,110,104,73635,BOURSE,Forfait Navigo,7400
319377,2025-12-17,100,110,481,73630,LOUVRE,Forfait Navigo,6046
83902,2025-12-21,100,110,907,71403,VILLIERS,Imagine R,1206
190534,2025-11-14,800,800,48092,64622,Lisière Pereire T13,Amethyste,11
85229,2025-10-07,800,803,638,63594,PETIT JOUY,Contrat Solidarite Transport,4
321462,2025-12-13,810,802,617,63067,PALAISEAU-VIL.,Contrat Solidarite Transport,118

In [18]:
donnees4.tail()

,jour,code_stif_trns,code_stif_res,code_stif_arret,id_zdc,libelle_arret,categorie_titre,nb_vald
480640,2025-10-04,800,852,797,463754,SEVRES RG,Forfait Navigo,657
480641,2025-10-04,800,852,813,73731,ST CYR,Contrat Solidarite Transport,217
480642,2025-10-04,800,852,938,63812,ST QUENTIN YVE,Amethyste,131
480643,2025-10-04,800,852,938,63812,ST QUENTIN YVE,Imagine R,1660
480644,2025-10-04,800,852,846,64194,TACOIGNIERES,Amethyste,1

In [19]:

donnees4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480645 entries, 0 to 480644
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   jour             480645 non-null  object
 1   code_stif_trns   480645 non-null  int64
 2   code_stif_res    480645 non-null  object
 3   code_stif_arret  480645 non-null  object
 4   id_zdc           480645 non-null  int64
 5   libelle_arret    480645 non-null  object
 6   categorie_titre  480645 non-null  object
 7   nb_vald          480645 non-null  int64
dtypes: int64(3), object(5)
memory usage: 29.3+ MB

# Concaténation des quatre fichiers en un dataframe Pandas - étude de ce dataframe

On utilise les dataframes issus de l'examen des fichiers dans la partie précédente. C'est pour cela qu'on n'a pas recours à une boucle `for`.

In [20]:
df = pd.concat((donnees1, donnees2, donnees3, donnees4))
# vérification de la longueur du dataframe concaténé
len(df) == len(donnees1) + len(donnees2) + len(donnees3) + len(donnees4)

True

In [21]:
df.sample(15)

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald,id_zdc
190597,2025-11-14,800,803,376,JAVEL,NaN,Contrat Solidarite Transport,423,71150.0
297171,2025-05-25,100,110,1229,CLICHY ST-OUEN,NaN,Contrat Solidarité Transport,785,72126.0
9112,2025-12-05,100,110,625,PARMENTIER,NaN,Forfaits courts,1762,71801.0
446777,2025-08-04,100,110,752,RUE DU BAC,NaN,Autres titres,33,71227.0
385069,2025-04-13,800,854,665,PONT-CARDINET,NaN,NON DEFINI,62,71475.0
153611,2025-12-24,800,850,281,FAREMOUTIERS,NaN,NON DEFINI,2,67917.0
103724,2025-10-13,800,854,831,ST NOM LA BRETE,NaN,NON DEFINI,1,64382.0
160237,2025-03-16,800,803,369,IVRY SUR SEINE,424396.0,Forfait Navigo,8,NaN
217347,2025-01-01,810,802,523,MASSY-VERRIER.,63320.0,Forfait Navigo,200,NaN
244094,2025-11-21,100,110,476,LOUIS BLANC,NaN,Imagine R,1492,71407.0
96240,2025-05-06,810,802,796,SEVRAN LIVRY,NaN,Amethyste,284,73439.0
56390,2025-08-24,800,854,92,BONNIERES,NaN,Contrat Solidarité Transport,41,66741.0
241918,2025-06-20,800,851,922,VULAINES SUR SE,NaN,Forfait Navigo,28,61630.0
209492,2025-04-29,800,804,530,MELUN GARE,NaN,Amethyste,374,61926.0
267681,2025-04-08,100,110,842,SULLY-MORLAND,NaN,Amethyste,138,71201.0

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1892453 entries, 0 to 480644
Data columns (total 9 columns):
 #   Column           Dtype
---  ------           -----
 0   jour             object
 1   code_stif_trns   int64
 2   code_stif_res    object
 3   code_stif_arret  object
 4   libelle_arret    object
 5   ida              float64
 6   categorie_titre  object
 7   nb_vald          int64
 8   id_zdc           float64
dtypes: float64(2), int64(2), object(5)
memory usage: 144.4+ MB

Dans le jeu de données, on ne conservera pas les champs `code_stif_arret`, `ida`, et `id_zdc`.
On filtrera les données intéressantes sur les champs `code_stif_trns` et `code_stif_res`.
On va prendre chaque colonne qu'on conservera ou sur laquelle on filtrera, la mettre en forme et le cas échéant vérifier sa conformité.

## Colonne `jour`
On convertit cette colonne en type `date`, puis on vérifie que chaque jour de l'année 2025 est bien présent (comparaison au set `annee`de l'ensemble des jours de 2025).

In [23]:
df["jour"] = pd.to_datetime(df["jour"])
annee = {datetime64("2025-01-01") + timedelta64(i) for i in range(365)}
print(set(df["jour"]) == annee)    # pd.unique(df["jour"]) peut calculer plus vite
                                    # ou annee.difference(set(df["jour"]))

True

## Colone `code_stif_trns`

Il s'agit du code du transporteur. Seule la RATP, code 100 nous intéresse.

In [24]:
pd.unique(df['code_stif_trns'])

array([100, 760, 762, 800, 810, 761, 764])

In [25]:
df = df[df['code_stif_trns'] == 100]

## Colonne `code_stif_res`

Il s'agit du code du réseau. Seul le code 110, correspondant au métro, nous intéresse.

In [26]:
pd.unique(df['code_stif_res'])

array(['110', 'ND'], dtype=object)

On doit éliminer les données du réseau 'ND'. Cependant on regarde avant la proportion de `nb_vald` (la variable quantitative que l'on va étudier) que cela représente.

In [27]:
df[df['code_stif_res']=='ND']['nb_vald'].sum()/df['nb_vald'].sum()

np.float64(0.000417352438591083)

Ce nombre est négligeable.

In [28]:
df = df[df['code_stif_res']=='110']

## Colonne `libelle_arret`

In [29]:
sorted(pd.unique(df['libelle_arret']))

['ABBESSES',
 'AIME CESAIRE',
 'ALESIA',
 'ALEXANDR.DUMAS',
 'ALFORT-ECOLE V',
 'ALMA-MARCEAU',
 'ANATOLE FRANCE',
 'ANTONY',
 'ANVERS',
 'ARGENTINE',
 'ARTS.METIERS',
 'ASSEMBLEE NAT.',
 'AUBERV.4 CHEM.',
 'AV.EMILE ZOLA',
 'AVRON',
 'BALARD',
 'BARBARA',
 'BARBES-ROCH.',
 'BASTILLE',
 'BEL AIR',
 'BELLEVILLE',
 'BERAULT',
 'BERCY',
 'BIBLIOTHEQUE',
 'BILLANCOURT',
 'BIR-HAKEIM',
 'BLANCHE',
 'BOB.P.PICASSO',
 'BOB.R.QUENEAU',
 'BOISSIERE',
 'BOLIVAR',
 'BONNE NOUVELLE',
 'BOTZARIS',
 'BOUCICAUT',
 'BOULETS-MONTR.',
 'BOULOGNE-J.J.',
 'BOULOGNE-ST.CL',
 'BOURSE',
 'BREGUET-SABIN',
 'BROCHANT',
 'BUTTES-CHAUM.',
 'BUZENVAL',
 'CADET',
 'CAMBRONNE',
 'CAMPO-FORMIO',
 'CARD.LEMOINE',
 'CARREF.PLEYEL',
 'CENSIER DAUB.',
 'CH.D.G.ETOILE',
 'CH.D.VINCENNES',
 'CHAMPS-ELYSEES',
 'CHARDON-LAGACH',
 'CHARENTON-ECO.',
 'CHARL.MICHELS',
 'CHARONNE',
 "CHATEAU D'EAU",
 'CHATEAU ROUGE',
 'CHATEAU-LANDON',
 'CHATELET',
 'CHATILLON-MON.',
 "CHAUSS.D'ANTIN",
 'CHEMIN-VERT',
 'CHEVALERET',
 'CHEVILLY-LARUE',
 'CITE',
 'CLICHY ST-OUEN',
 'COLONEL FABIEN',
 'COMMERCE',
 'CONCORDE',
 'CONVENTION',
 'CORENT.CARIOU',
 'CORENT.CELTON',
 'CORVISART',
 'COT. BEAUCLAIR',
 'COUR ST-EMILI.',
 'COURCELLES',
 'COURONNES',
 'CRETEIL-ECHAT',
 'CRETEIL-P. LAC',
 'CRETEIL-PREF.',
 'CRETEIL-UNIV.',
 'CRIMEE',
 'CRX.DE CHAVAUX',
 'DANUBE',
 'DAUMESNIL',
 'DENFERT-ROCH.',
 'DUGOMMIER',
 'DUPLEIX',
 'DUROC',
 'EC.MILITAIRE',
 'EDGAR QUINET',
 "EGLI.D'AUTEUIL",
 'EGLI.DE PANTIN',
 'ESPLANADE DEF.',
 'ETIENNE MARCEL',
 'EUROPE',
 'EXELMANS',
 'F.D.ROOSEVELT',
 'FAIDHERBE-CHA.',
 'FALGUIERE',
 'FELIX FAURE',
 'FILLES DU CALV',
 "FORT D'AUBERV.",
 'FR. POPULAIRE',
 'FUNICULAIRE',
 'GABRIEL PERI',
 'GAITE',
 'GALLIENI',
 'GAMBETTA',
 "GARE D'AUSTER.",
 "GARE DE L'EST",
 'GARE DE LYON',
 'GARE DU NORD',
 'GARIBALDI',
 'GDS BOULEVARDS',
 'GEORGE V',
 'GLACIERE',
 'GONCOURT',
 'GUY MOQUET',
 'HAVR.CAUMARTIN',
 'HOCHE',
 'HOP. BICETRE',
 'HOTEL DE VILLE',
 'IENA',
 'INVALIDES',
 'J.BONSERGENT',
 'JASMIN',
 'JAURES',
 'JAVEL',
 'JOURDAIN',
 'JULES JOFFRIN',
 'JUSSIEU',
 'KLEBER',
 'KREML.BICETRE',
 "L'HAY-LES-ROSE",
 'LA CHAPELLE',
 'LA COURNEUVE',
 'LA DEFENSE',
 'LA DHUYS',
 'LA FOURCHE',
 'LA MOTTE-PICQ.',
 'LA MUETTE',
 'LAMARCK-CAUL.',
 'LATOUR-MAUB.',
 'LAUMIERE',
 'LE PELETIER',
 'LEDRU-ROLLIN',
 'LES AGNETTES',
 'LES COURTILLES',
 'LES GOBELINS',
 'LES HALLES',
 'LES SABLONS',
 'LIBERTE',
 'LIEGE',
 'LOUIS BLANC',
 'LOUISE MICHEL',
 'LOURMEL',
 'LOUVRE',
 'LUCIE AUBRAC',
 'M. MONTROUGE',
 'M.ANGE-AUTEUIL',
 'M.ANGE-MOLITOR',
 'MABILLON',
 'MADELEINE',
 'MAIRIE CLICHY',
 "MAIRIE D'AUBERVILLIERS",
 "MAIRIE D'ISSY",
 "MAIRIE D'IVRY",
 'MAIRIE D.LILAS',
 'MAIRIE D.MONT',
 'MAIRIE ST-OUEN',
 'MAIS.ALF-JUIL.',
 'MAIS.ALF-STADE',
 'MAISON BLANCHE',
 'MALAK-P.VANVES',
 'MALAK.ET.DOLET',
 'MALESHERBES',
 'MARAICHERS',
 'MARCADET-POIS.',
 'MARCEL SEMBAT',
 'MARX DORMOY',
 'MAUBERT-MUTUA.',
 'MENILMONTANT',
 'MICHEL BIZOT',
 'MIRABEAU',
 'MIROMESNIL',
 'MONCEAU',
 'MONTGALLET',
 'MONTPARNASSE',
 'MONTREUIL HOP.',
 'MOUTON-DUVERN.',
 'N.D.DE-LORETTE',
 'N.D.DES-CHAMPS',
 'NATION',
 'NATIONALE',
 'OBERKAMPF',
 'ODEON',
 'OLYMPIADES',
 'OPERA',
 'OURCQ',
 'PALAIS-ROYAL',
 'PARMENTIER',
 'PASSY',
 'PASTEUR',
 'PELLEPORT',
 'PERE-LACHAISE',
 'PEREIRE',
 'PERNETY',
 'PHIL.AUGUSTE',
 'PICPUS',
 'PIERRE CURIE',
 'PIGALLE',
 'PLACE CLICHY',
 "PLACE D'ITALIE",
 'PLACE D. FETES',
 'PLACE MONGE',
 'PLAISANCE',
 'POISSONNIERE',
 'PONT CARDINET',
 'PONT D.NEUILLY',
 'PONT DE SEVRES',
 'PONT LEVALLOIS',
 'PONT MARIE',
 'PONT-NEUF',
 "PORTE D'ITALIE",
 "PORTE D'IVRY",
 'PORTE D.CLIGN.',
 'PORTE D.LILAS',
 'PORTE D.VANVES',
 'PORTE D.VERS.',
 'PORTE DAUPHINE',
 'PORTE DOREE',
 'PORTE MAILLOT',
 'PRE-ST-GERVAIS',
 'PTE CHAMPERRET',
 'PTE CHARENTON',
 "PTE D'AUTEUIL",
 "PTE D'ORLEANS",
 'PTE D. VINCENN',
 'PTE D.BAGNOLET',
 'PTE D.CHAPELLE',
 'PTE D.ST-OUEN',
 'PTE D.VILLETTE',
 'PTE DE CHOISY',
 'PTE DE CLICHY',
 'PTE DE PANTIN',
 'PTE MONTREUIL',
 'PTE ST-CLOUD',
 'PYRAMIDES',
 'PYRENEES',
 'QUAI D.LA GARE',
 'QUAI.LA RAPEE',
 'QUATRE-SEPTEMB',
 'RAMBUTEAU',
 'RANELAGH',
 'RASPAIL',
 'REAUMUR-SEB.',
 'RENNES',
 'REPUBLIQUE',
 'REUILLY-DID.',
 'RICHARD LENOIR',
 'RICHELIEU-DR.',
 'RIQUET',
 'ROBESPIERRE',
 'ROMAINV.CARNOT',
 'ROME',
 'ROSNY BOIS.P',
 'RUE D.LA POMPE',
 'RUE DU BAC',
 'S. GAINSBOURG',
 'SAINT-AMBROISE',
 'SAINT-AUGUSTIN',
 'SAINT-FARGEAU',
 'SAINT-GEORGES',
 'SAINT-JACQUES',
 'SAINT-LAZARE',
 'SAINT-MARCEL',
 'SAINT-MAUR',
 'SAINT-MICHEL',
 'SAINT-PAUL',
 'SAINT-PLACIDE',
 'SAINT-SULPICE',
 'SEGUR',
 'SENTIER',
 'SEVRES-BABYL.',
 'SEVRES-LECOUR.',
 'SIMPLON',
 'SOLFERINO',
 'ST-DENIS-BASIL',
 'ST-DENIS-PTE P',
 'ST-DENIS-UNIV.',
 'ST-FRAN.XAVIER',
 'ST-GERM.D.PRES',
 'ST-MANDE TOUR.',
 'ST-PH.DU-ROULE',
 'ST-SEBASTIEN.F',
 'STALINGRAD',
 'STRAS.ST-DENIS',
 'SULLY-MORLAND',
 'TELEGRAPHE',
 'TEMPLE',
 'TERNES',
 'THIAIS-ORLY',
 'TOLBIAC',
 'TRINITE',
 'TROCADERO',
 'TUILERIES',
 'VANEAU',
 'VARENNE',
 'VAUGIRARD',
 'VAVIN',
 'VICTOR HUGO',
 'VILLEJ.L.ARAG.',
 'VILLEJ.L.LAGR.',
 'VILLEJ.P.V.C',
 'VILLIERS',
 'VOLONTAIRES',
 'VOLTAIRE',
 'WAGRAM']

En comparant à lal liste des stations de métro <https://fr.wikipedia.org/wiki/Liste_des_stations_du_m%C3%A9tro_de_Paris>, on note la présence de deux stations supplémentaires dans notre jeu de données :
- ANTONY : pourquoi ?
- FUNICULAIRE : on conserve cette station.

In [30]:
df[df['libelle_arret'] == 'ANTONY']

,jour,code_stif_trns,code_stif_res,code_stif_arret,libelle_arret,ida,categorie_titre,nb_vald,id_zdc
4743,2025-09-24,100,110,19,ANTONY,NaN,Forfaits courts,2,69759.0
134536,2025-09-11,100,110,19,ANTONY,NaN,NON DEFINI,1,69759.0
146054,2025-09-10,100,110,19,ANTONY,NaN,Forfait Navigo,1,69759.0
150479,2025-09-22,100,110,19,ANTONY,NaN,Forfait Navigo,1,69759.0
175401,2025-09-29,100,110,19,ANTONY,NaN,Forfaits courts,1,69759.0
176491,2025-09-25,100,110,19,ANTONY,NaN,Forfaits courts,1,69759.0
274400,2025-09-11,100,110,19,ANTONY,NaN,Contrat Solidarité Transport,1,69759.0
39360,2025-11-19,100,110,19,ANTONY,NaN,Contrat Solidarite Transport,1,69759.0
55100,2025-11-07,100,110,19,ANTONY,NaN,Forfait Navigo,2,69759.0
119593,2025-11-19,100,110,19,ANTONY,NaN,Forfaits courts,6,69759.0
380424,2025-11-14,100,110,19,ANTONY,NaN,Forfait Navigo,2,69759.0
476232,2025-10-08,100,110,19,ANTONY,NaN,Forfait Navigo,1,69759.0

Au vu des très faibles effectifs, il s'agit vraisemblablement d'une erreur. On supprime ces occurrences :

In [31]:
df = df[df['libelle_arret'] != "ANTONY"]

On note également 4 stations manquantes :
- *Villejuif-Gustave-Roussy* : ouverte en janvier 2025 et non exploitée par la RATP,
- *Aéroport d'Orly* : tarification spécifique et non exploitée par la RATP,
- *Saint-Denis-Pleyel* : non exploitée par la RATP,
- *Cluny-La-Sorbonne* : *peut-être* du fait de sa liaison avec *Saint-Michel* ? Pas d'explicaton formelle.

## Colonne `categorie_titre`

In [32]:
pd.unique(df['categorie_titre'])

array(['Forfaits courts', 'Autres titres', 'Contrat Solidarité Transport',
       'Forfait Navigo', 'Imagine R', 'Amethyste', 'NON DEFINI',
       'Contrat Solidarite Transport'], dtype=object)

**On remarque la présence de "Contrat Solidarité Transport" *et* de "Contrat Solidarite Transport" ; on corrige ce dernier libellé :**

In [33]:
df = df.replace("Contrat Solidarite Transport", "Contrat Solidarité Transport")
pd.unique(df['categorie_titre'])

array(['Forfaits courts', 'Autres titres', 'Contrat Solidarité Transport',
       'Forfait Navigo', 'Imagine R', 'Amethyste', 'NON DEFINI'],
      dtype=object)

On calcule la proportion de `nb_valid` avec `categorie_titre` 'NON DEFINI' :

In [34]:
df[df['categorie_titre']=='NON DEFINI']['nb_vald'].sum()/df['nb_vald'].sum()

np.float64(0.010595519436082146)

On choisit de conserver cette modalité, bien que peu significative.

## Colonne `nb_vald`

Il s'agit de la seule colonne quantitative que nous allons étudier

In [35]:
df['nb_vald'].groupby(df['categorie_titre']).describe()

,count,mean,std,min,25%,50%,75%,max
categorie_titre,,,,,,,,
Amethyste,114974.0,256.423000,229.219000,1.0,110.0,193.0,318.00,2693.0
Autres titres,114908.0,204.790250,394.783402,1.0,52.0,98.0,209.00,12481.0
Contrat Solidarité Transport,115102.0,1005.118304,1143.164582,1.0,374.0,666.0,1200.00,14491.0
Forfait Navigo,115454.0,5655.685234,5722.240091,1.0,2610.0,4333.0,6882.75,92195.0
Forfaits courts,115014.0,1917.825665,2674.105964,1.0,721.0,1163.0,1966.75,42157.0
Imagine R,115046.0,1758.261391,1716.595560,1.0,787.0,1350.0,2178.00,30768.0
NON DEFINI,115904.0,114.989146,129.726791,1.0,44.0,72.0,128.00,1400.0

**On remarque qu'il y a des valeurs inférieures à 5, contrairement à ce qui est spécifié dans la documentation du jeu de données.**

## Création du fichier source

### Suppression des colonnes inutiles

In [36]:
df = df.drop(['code_stif_trns', 'code_stif_res', 'code_stif_arret', 'ida', 'id_zdc'], axis=1)
df

             jour   libelle_arret               categorie_titre  nb_vald
0      2025-03-07       MADELEINE               Forfaits courts     3387
1      2025-03-07    BARBES-ROCH.                 Autres titres      478
2      2025-03-07   S. GAINSBOURG  Contrat Solidarité Transport      781
3      2025-03-07   S. GAINSBOURG                Forfait Navigo     2880
4      2025-03-07   S. GAINSBOURG                     Imagine R     1158
...           ...             ...                           ...      ...
480466 2025-10-04  VILLEJ.L.LAGR.                 Autres titres       49
480467 2025-10-04  VILLEJ.L.LAGR.  Contrat Solidarité Transport      591
480468 2025-10-04     VOLONTAIRES                 Autres titres       45
480469 2025-10-04     VOLONTAIRES  Contrat Solidarité Transport      226
480470 2025-10-04     VOLONTAIRES               Forfaits courts     1158

[806402 rows x 4 columns]

### Recherche de lignes doublonnées

Le jeu données ne devrait *théoriquement* plus comporter de **doublons (même jour, même arrêt, même catégorie de titre)**, mais il faut le verifier :

In [37]:
df_agr = df.groupby(
    ["jour", "libelle_arret", "categorie_titre"]
)["nb_vald"].count()

doublons = df_agr[df_agr > 1]
doublons

jour        libelle_arret   categorie_titre
2025-01-01  MAIRIE ST-OUEN  Amethyste                       2
                            Autres titres                   2
                            Contrat Solidarité Transport    2
                            Forfait Navigo                  2
                            Forfaits courts                 2
                                                           ..
2025-12-31  PTE DE CLICHY   Contrat Solidarité Transport    2
                            Forfait Navigo                  2
                            Forfaits courts                 2
                            Imagine R                       2
                            NON DEFINI                      2
Name: nb_vald, Length: 5689, dtype: int64

On trouve un **grand nombre de doublons**, qu'il va falloir examminer :

In [38]:
doublons.sample(10)

jour        libelle_arret   categorie_titre
2025-08-28  MAIRIE ST-OUEN  Forfaits courts                 2
2025-05-10  MAIRIE ST-OUEN  Forfaits courts                 2
2025-11-12  MAIRIE ST-OUEN  Forfaits courts                 2
2025-08-17  MAISON BLANCHE  Contrat Solidarité Transport    2
2025-02-03  MAISON BLANCHE  NON DEFINI                      2
2025-05-08  MAIRIE ST-OUEN  NON DEFINI                      2
2025-03-12  MAIRIE ST-OUEN  Forfaits courts                 2
2025-04-20  MAIRIE ST-OUEN  Amethyste                       2
2025-11-02  MAISON BLANCHE  NON DEFINI                      2
2025-10-05  MAISON BLANCHE  Contrat Solidarité Transport    2
Name: nb_vald, dtype: int64

In [39]:
pd.unique(doublons.reset_index()["libelle_arret"])

array(['MAIRIE ST-OUEN', 'MAISON BLANCHE', 'PTE DE CLICHY'], dtype=object)

Ces doublons ne concernent donc que **trois stations**.

In [40]:
len(pd.unique(doublons.reset_index()["jour"]))

365

Mais ils s'étalent sur **toute l'année**.
On examine un échantillon de ces doublons, en faisant tourner plusieurs fois le code suivant :

In [42]:
# Échantillon du jeu de données sur 1 date aléatoire, pour les 3 stations présentant des doublons
df[(df["libelle_arret"].isin(pd.unique(doublons.reset_index()["libelle_arret"]))) \
    & (df["jour"].isin(df["jour"].sample(1)))] \
    .sort_values(["jour", "libelle_arret", "categorie_titre"])

             jour   libelle_arret               categorie_titre  nb_vald
76742  2025-04-29  MAIRIE ST-OUEN                     Amethyste      169
434477 2025-04-29  MAIRIE ST-OUEN                     Amethyste      263
209073 2025-04-29  MAIRIE ST-OUEN                 Autres titres       46
434478 2025-04-29  MAIRIE ST-OUEN                 Autres titres      165
76743  2025-04-29  MAIRIE ST-OUEN  Contrat Solidarité Transport      939
172887 2025-04-29  MAIRIE ST-OUEN  Contrat Solidarité Transport     2303
76555  2025-04-29  MAIRIE ST-OUEN                Forfait Navigo    11512
76744  2025-04-29  MAIRIE ST-OUEN                Forfait Navigo     3406
209074 2025-04-29  MAIRIE ST-OUEN               Forfaits courts      637
350059 2025-04-29  MAIRIE ST-OUEN               Forfaits courts     1760
434479 2025-04-29  MAIRIE ST-OUEN                     Imagine R     2390
434658 2025-04-29  MAIRIE ST-OUEN                     Imagine R      728
209075 2025-04-29  MAIRIE ST-OUEN                    NON DEFINI       50
350060 2025-04-29  MAIRIE ST-OUEN                    NON DEFINI      156
76697  2025-04-29  MAISON BLANCHE                     Amethyste      336
434664 2025-04-29  MAISON BLANCHE                     Amethyste      158
209084 2025-04-29  MAISON BLANCHE                 Autres titres       59
434617 2025-04-29  MAISON BLANCHE                 Autres titres      120
76698  2025-04-29  MAISON BLANCHE  Contrat Solidarité Transport     1409
434665 2025-04-29  MAISON BLANCHE  Contrat Solidarité Transport      526
76747  2025-04-29  MAISON BLANCHE                Forfait Navigo     2955
173060 2025-04-29  MAISON BLANCHE                Forfait Navigo     6682
350168 2025-04-29  MAISON BLANCHE               Forfaits courts     1138
434666 2025-04-29  MAISON BLANCHE               Forfaits courts      440
173118 2025-04-29  MAISON BLANCHE                     Imagine R      982
350169 2025-04-29  MAISON BLANCHE                     Imagine R     2950
209085 2025-04-29  MAISON BLANCHE                    NON DEFINI       35
350170 2025-04-29  MAISON BLANCHE                    NON DEFINI      167
434745 2025-04-29   PTE DE CLICHY                     Amethyste      787
76844  2025-04-29   PTE DE CLICHY                 Autres titres      864
173204 2025-04-29   PTE DE CLICHY  Contrat Solidarité Transport     3622
76845  2025-04-29   PTE DE CLICHY                Forfait Navigo    17007
209180 2025-04-29   PTE DE CLICHY               Forfaits courts     2994
76846  2025-04-29   PTE DE CLICHY                     Imagine R     5625
350292 2025-04-29   PTE DE CLICHY                    NON DEFINI      312

**Conclusion : les lignes en doublon comportent des nombres de validations à la fois significatifs *et* différents. En l'absence d'explication, on décide de les *agréger par somme*.**

### Traitement par agrégation des lignes en doublon

In [43]:
# as_index=False : très important pour garder un jeu de données exportable proprement !
df = df.groupby(by=['jour', 'libelle_arret', 'categorie_titre'], as_index=False).aggregate("sum")
df

             jour libelle_arret               categorie_titre  nb_vald
0      2025-01-01      ABBESSES                     Amethyste       18
1      2025-01-01      ABBESSES                 Autres titres     1042
2      2025-01-01      ABBESSES  Contrat Solidarité Transport       96
3      2025-01-01      ABBESSES                Forfait Navigo     1302
4      2025-01-01      ABBESSES               Forfaits courts     1059
...           ...           ...                           ...      ...
800708 2025-12-31        WAGRAM  Contrat Solidarité Transport      180
800709 2025-12-31        WAGRAM                Forfait Navigo     1517
800710 2025-12-31        WAGRAM               Forfaits courts      620
800711 2025-12-31        WAGRAM                     Imagine R      349
800712 2025-12-31        WAGRAM                    NON DEFINI       20

[800713 rows x 4 columns]

### Export du fichier des données traitées

Le fichier est exporté dans le répertoire parent de celui depuis lequel ce notebook est lancé. Selon l'arborescence du projet, cela correspond au **répertoire racine du projet**.

In [44]:
# durée : environ 1 min 30
df.to_excel("../data_traitee.xlsx", sheet_name="DATA", na_rep="NA", index=False)